### ISSUE TITLE
"Generate Sources and and Update Folders for all projects" does not work in Intellij

### ISSUE THREAD

**Issue by oliviercoma** [graphql-java-generator/graphql-maven-plugin-project#103]
Hello,

The plugin fails to generate sources under Intellij and actually crashes the whole generation process when using the "Generate Sources and Update Folders for all projects" functionality.

The reason is that velocity tries to log into "velocity.log" in the current working directory. However, the current working directory is the bin folder of Intellij and is not writeable
Following Maven documentation for plugin developers, it should not be assumed what the working directory is, and Intllij behavior is allowed ( http://maven.apache.org/plugin-developers/common-bugs.html#Resolving_Relative_Paths ).

This SO topic ( https://stackoverflow.com/questions/46621916/change-the-location-of-velocity-log-file ) suggests that to change the directory, the "runtime.log" Velocity property should be set.

As a quick fix, I've put my bin folder as writeable. The velocity.log file is indeed created in that folder and the generation succeeds.

**Comment by etienne-sf** [comment]
Hello,

I don't understand very well this issue. I have no `velocity.log` file after a maven build.
When an error occurs, it is logged through the maven logger.

Did you change something in the plugin configuration ?

And, of course I can change the folder. But again, I don't understand this `bin` folder.
Is this an Intellij one ?

Etienne

**Comment by oliviercoma** [comment]
Hello,

Thanks for your reply. Indeed, I never noticed this file when executing maven from the command line before. Configuration is quite basic I think (see below). But it's possible that Intellij interferes in some way? Not sure. 

Regarding the bin folder, it was not clear. Yes it's Intllij bin folder.

`
<plugin>
				<groupId>com.graphql-java-generator</groupId>
				<artifactId>graphql-maven-plugin</artifactId>
				<version>${graphql-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>graphql</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>generateServerCode</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<mode>server</mode>
					<packageName>be.sprk.gql</packageName>
					<scanBasePackages>be.sprk.bolt</scanBasePackages>
					<schemaFileFolder>src/main/resources/gql</schemaFileFolder>
					<copyRuntimeSources>false</copyRuntimeSources>
					<generateDeprecatedRequestResponse>false</generateDeprecatedRequestResponse>
					<separateUtilityClasses>true</separateUtilityClasses>
					<javaTypeForIDType>java.lang.String</javaTypeForIDType>
					<customScalars>
						<customScalar>
							<graphQLTypeName>Date</graphQLTypeName>
							<javaType>java.time.LocalDate</javaType>
							<graphQLScalarTypeStaticField>be.sprk.bolt.utils.gql.DateScalarType.Date</graphQLScalarTypeStaticField>
						</customScalar>
						<customScalar>
							<graphQLTypeName>DateTime</graphQLTypeName>
							<javaType>java.time.LocalDateTime</javaType>
							<graphQLScalarTypeStaticField>be.sprk.bolt.utils.gql.DateTimeScalarType.DateTime</graphQLScalarTypeStaticField>
						</customScalar>
					</customScalars>
					<skipGenerationIfSchemaHasNotChanged>true</skipGenerationIfSchemaHasNotChanged>
				</configuration>
			</plugin>
`

**Comment by etienne-sf** [comment]
The issue here is: how can I test any correction, as this file is not generated for me ?

Would it be possible for you to build the snapshot version (once I commit it), and check the correction, before I release it ?

Étienne

**Comment by oliviercoma** [comment]
Hello,

Sorry, I missed your answer. Sure, no problem.

**Comment by etienne-sf** [comment]
Hello,

I commited an upgrade of Velocity, from 1.7 to 2.3.

Now, Velocity uses slf4j, as a logging framework. So the velocity logging should go in the place as all the other logging stuff.

This should solve this issue. Can you check it ?

Etienne

**Comment by etienne-sf** [comment]
This should be solved in the 1.18.1 release, after upgrade to Velocity 2.3.

Velocity now uses slf4j, and its logging should occur according to the plugin's configuration

**Comment by oliviercoma** [comment]
Thanks, that solves the issue indeed !
