### ISSUE TITLE
Allow custom ExchangeFilterFunction in reactive WebClient configuration

### ISSUE THREAD

**Issue by thmsckldt** [graphql-java-generator/graphql-maven-plugin-project#105]
This is the same request as mentioned in https://github.com/graphql-java-generator/graphql-maven-plugin-project/issues/87. 

But in the current plugin version 1.17.3 there is no GraphQLAutoConfiguration class in the runtime any more. Instead the Spring configuration is a generated class ("SpringConfiguration.java"). This is not a Spring Auto Configuration (the META-INF/spring.factories file is missing) and the bean annotations have no @ConditionalOnMissingBean, so it is not possible to override the preconfigured WebClient instance. If you try with Spring Boot defaults you get the error "A bean with that name has already been defined in class path resource".

My suggestion is make the generated SpringConfiguration a Spring Auto Configuration to allow overriding all configuration items.

**Comment by etienne-sf** [comment]
Hello,

That is strange to me as I thought that any number of ´ExchangeFilterFunction´ can be found by Spring. 
But I didn't check that it is possible to see other ´ExchangeFilterFunction´ Spring beans. 

Do you want to override the existing one? Or to add a new one ?

Étienne

**Comment by thmsckldt** [comment]
Hello,

I want to add a new ExchangeFilterFunction and override the WebClient configuration from class SpringConfiguration, like this:

```
    @Bean
    public WebClient webClient(@Autowired String graphqlEndpoint, //
                               @Autowired(required = false) @Qualifier("httpClient") HttpClient httpClient,
                               @Autowired(required = false) @Qualifier("serverOAuth2AuthorizedClientExchangeFilterFunction") ServerOAuth2AuthorizedClientExchangeFilterFunction serverOAuth2AuthorizedClientExchangeFilterFunction,
                               @Autowired(required = false) @Qualifier("userTokenPropagator") UserTokenPropagator userTokenPropagator) {

        return GraphQLConfiguration.getWebClient(graphqlEndpoint, httpClient,
                serverOAuth2AuthorizedClientExchangeFilterFunction, userTokenPropagator);
    }

```

But this leads to the error "A bean with that name has already been defined in class path resource".

**Comment by Sharofiddin** [comment]
I experienced this issue too. I should add an HTTP header to the request but it seems I have to change generated codes.

**Comment by etienne-sf** [comment]
Ok, here is the solution I found for this issue:

Adding the `@ConditionalOnMissingBean` in the generated SpringConfiguration class doesn't help. I think it works only in auto-configuration class (it's not that clear in the Spring doc).

But there is a Spring configuration parameter for that:

```
spring.main.allow-bean-definition-overriding = true 
```

As stated in the error message, this parameter allows an application to override an existing bean.

My recommandation is to mark the overriding bean with the `@Primary` annotation (but it doesn't seem to be mandatory), for instance:

```java
	@Bean
	public WebClient webClientAllGraphQLCases(String graphqlEndpointAllGraphQLCases, //
			@Autowired(required = false) @Qualifier("httpClientAllGraphQLCases") HttpClient httpClientAllGraphQLCases,
			@Autowired(required = false) @Qualifier("serverOAuth2AuthorizedClientExchangeFilterFunctionAllGraphQLCases") ServerOAuth2AuthorizedClientExchangeFilterFunction serverOAuth2AuthorizedClientExchangeFilterFunctionAllGraphQLCases,
...
your own exchange filter functions or other specific parameters
...) {
		return GraphQLConfiguration.getWebClient(graphqlEndpointAllGraphQLCases, httpClientAllGraphQLCases,
				serverOAuth2AuthorizedClientExchangeFilterFunctionAllGraphQLCases,
				... your own exchange filters
				);
	}
```


Does it help ?


Etienne

**Comment by thmsckldt** [comment]
I agree with Sharofiddin. _allow-bean-definition-overriding_ has been disabled by default in Spring Boot 2.1 (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes) and is not considered best practice. 

My working solution so far is to edit the generated class SpringConfiguration and add the @ConditionalOnMissingBean annotation to the _webClient_ method. You are right that this will work only for auto-configuration beans and it's easy to make SpringConfiguration an auto-configuration bean: simply add a file META-INF/spring.factories to the classpath with content 

`org.springframework.boot.autoconfigure.EnableAutoConfiguration=<package-name>.SpringConfiguration`

(see https://docs.spring.io/spring-boot/docs/2.0.0.M3/reference/html/boot-features-developing-auto-configuration.html)

So if you add the spring.factories file to the generator and add the @ConditionalOnMissingBean annotation in SpringConfiguration everything should work as expected.

**Comment by etienne-sf** [comment]
> I think this is not a solution, this is a workaround. I think users should be able to inject their HttpHeaders without affecting spring's core configurations.

I plainly agree with that.

> it's easy to make SpringConfiguration an auto-configuration bean: simply add a file META-INF/spring.factories to the classpath with content

Yes, this is the way (without being a Mandalorian :) )
I guess I can generate an auto-configuration file, instead of configuration file. In previous versions the runtime contained such an auto-configuration file.

I'll work on that for the next release, which seems to be quite ready.


Etienne Gauthier

**Comment by etienne-sf** [comment]
I just commited an update, so that the generated Spring configuration is now an auto configuration file.

It will be available in the next version

Etienne

**Comment by thmsckldt** [comment]
Cool, i'm looking forward the next version!

**Comment by etienne-sf** [comment]
It is available in the 1.18, that has just been released.

Etienne

**Comment by michaelhunziker** [comment]
@etienne-sf Does this mean there is no more need to set "allow-bean-definition-overriding: true"?

I was just following the instructions here which state otherwise: https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/client_faq#add-new-exchange-filter-function-includes-add-specific-headers-to-the-request

**Comment by etienne-sf** [comment]
Right, this should not be useful anymore. 

I'll check that, and correct the doc if I confirm this.

**Comment by etienne-sf** [comment]
The FAQ had not been updated after 1.18. 
So if you use 1.18 or latter, you can use the ´@Primary´ again (and remove the use of ´allow-bean-definition-overriding´)

I'll publish an updated version of the wiki

**Comment by michaelhunziker** [comment]
Hi @etienne-sf 

Thanks for your quick response!

For me it is not working using @Primary and removing `allow-bean-definition-overriding: true`:

This is my configuration where I am trying to override the `webClient` Bean:

```
package com.occ.offertool.shared.configurations;


import com.graphql_java_generator.client.GraphQLConfiguration;
import com.occ.offertool.graphql.util.QueryExecutor;
import org.apache.http.HttpHeaders;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.http.MediaType;
import org.springframework.http.client.reactive.ReactorClientHttpConnector;
import org.springframework.security.oauth2.client.web.reactive.function.client.ServerOAuth2AuthorizedClientExchangeFilterFunction;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.netty.http.client.HttpClient;

import java.util.Collections;

@Configuration
@ComponentScan(basePackageClasses = { GraphQLConfiguration.class, QueryExecutor.class })
public class OccGraphQLConfiguration {

    private final String websiteSchemaToken;

    public OccGraphQLConfiguration(@Value("${graphql.endpoint.websiteSchemaToken}") String websiteSchemaToken) {
        this.websiteSchemaToken = websiteSchemaToken;

    }

    @Bean
    @Primary
    public WebClient webClient(@Autowired(required = false) String graphqlEndpoint, @Autowired(required = false) HttpClient httpClient,
                               @Autowired(required = false) ServerOAuth2AuthorizedClientExchangeFilterFunction oauthFilter) {
        final WebClient.Builder webClientBuilder = WebClient.builder()//
                .baseUrl(graphqlEndpoint)//
                .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                .defaultHeader(HttpHeaders.AUTHORIZATION, "Bearer " + websiteSchemaToken)
                .defaultUriVariables(Collections.singletonMap("url", graphqlEndpoint));

        if (httpClient != null) {
            webClientBuilder.clientConnector(new ReactorClientHttpConnector(httpClient));
        }
        if (oauthFilter != null) {
            webClientBuilder.filter(oauthFilter);
        }

        return webClientBuilder.build();
    }


}

```






**Error message:**

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'webClient', defined in class path resource [com/occ/offertool/shared/configurations/OccGraphQLConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/occ/offertool/graphql/spring_autoconfiguration/SpringConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'webClient' defined in class path resource [com/occ/offertool/shared/configurations/OccGraphQLConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=true; factoryBeanName=occGraphQLConfiguration; factoryMethodName=webClient; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/occ/offertool/shared/configurations/OccGraphQLConfiguration.class]] for bean 'webClient': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=springConfiguration; factoryMethodName=webClient; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/occ/offertool/graphql/spring_autoconfiguration/SpringConfiguration.class]] bound.

```


**My dependencies:**

```
graphql-java-client-runtime: 1.18.9
spring boot: 2.6.6
```

**Comment by etienne-sf** [comment]
Hum, hum,

I think the issue is that the generated Spring autoconfiguration is not seen as an auto-configuration file, but is scanned by Spring. 

Can you check if the generated Spring autoconfiguration is in a sub package of either:
* The Main class's one
* A package scanned by one of the ´@ComponentScan´ annotations (including the ´@SpringBootApplication´ annotation)

**Comment by michaelhunziker** [comment]
This is the generated Spring Boot auto configuration:

```
package com.occ.offertool.graphql.spring_autoconfiguration;
...
@Configuration("springConfiguration") // The name of this bean will be springConfiguration
@ComponentScan("com.occ.offertool.graphql.util")
@SuppressWarnings("unused")
public class SpringConfiguration {
   ...
}
```


Main class:
```
package com.occ.offertool;
...
@SpringBootApplication(exclude = {SecurityAutoConfiguration.class})
@ServletComponentScan
public class OfferToolApplication {
   ...
}
```

**Comment by etienne-sf** [comment]
Ok, that is the issue : the generated Spring autoconfiguration is in a subpackage of the main class. So it is read as a standard configuration class, and not as a Spring autoconfiguration class.
To do the trick, I think you just have to exclude also the `com.occ.offertool.graphql.spring_autoconfiguration.SpringConfiguration` class in the `@SpringBootApplication` of the `OfferToolApplication` class.
