### ISSUE TITLE
Support for fragments

### ISSUE THREAD

**Issue by vikramp** [graphql-java-generator/graphql-maven-plugin-project#106]
I am getting an error when I use fragment in my schema during startup as below
Caused by: graphql.schema.idl.errors.SchemaProblem: errors=[The schema definition text contains a non schema definition language (SDL) element 'FragmentDefinition']
	at graphql.schema.idl.SchemaParser.buildRegistry(SchemaParser.java:156) ~[graphql-java-17.3.jar:na]
	at graphql.schema.idl.SchemaParser.parseImpl(SchemaParser.java:124) ~[graphql-java-17.3.jar:na]
	at graphql.schema.idl.SchemaParser.parseImpl(SchemaParser.java:111) ~[graphql-java-17.3.jar:na]

**Comment by etienne-sf** [comment]
This error is raised by graphql-java, which is the official Java implementation for graphQL. So the error is probably within your GraphQL schema.

Can you provide the schema, or the part of schema that causes this issue ?

Etienne

**Comment by vikramp** [comment]
Thanks for the response. Please find the schema definition below. Please suggest.
Note: The maven steps clean , compile works well. It is during my spring boot startup that I face the error listed above.

Regards
Vikram Pancholi

type PriceCatalog {
    catalogItem: CatalogItem!
    unitPrice: UnitPrice!
    applicableFrom: String!
    applicableTo: String
    latestExtendedOn: String
    """ Show first and last and implement pagination for the others, implement fragment for PriceRecommendation to include date, id """
    linkedPriceRecommendations: [PriceRecommendation]
}

fragment PriceCatalogBase on PriceCatalog{
    catalogItem { id}
    unitPrice { price unit currency}
    applicableFrom
    applicableTo
    latestExtendedOn
}

**Comment by etienne-sf** [comment]
The GraphQL document is very unclear in this point.

But AFAIU, you can not defined a Fragment in your GraphQL schema. Fragment are only defined in queries.

Etienne

**Comment by etienne-sf** [comment]
Hello,

The GraphQL spec is not very clear to me on this point.

But I think you may not define Fragments in a GraphQL schema. Try define them only in your queries, instead.


Etienne

**Comment by Latsode** [comment]
Hello, 

I am relatively new to all these but I can speak from my experience . I dont have single fragment defined in schema file , but I can still send Full requests such as this one without any problems.
![image](https://user-images.githubusercontent.com/89033725/141952049-875db4ae-d56f-4e3c-9d00-2c5d3393848e.png)
example of java code that works (I know this is horrible way to build query but only used it for testing )
```java
    @Override
    public CollectionConnection getCollections(Integer first, String after, CollectionSortKeys collectionSortKeys) throws GraphQLRequestPreparationException, GraphQLRequestExecutionException {
        GraphQLRequest graphQLFullRequest = new GraphQLRequest("query{\n" +
                "\tcollections(first : " + first + "){\n" +
                "    edges{\n" +
                "      \n" +
                "      node{\n" +
                "        id\n" +
                "        __typename\n" +
                "        title\n" +
                "        handle\n" +
                "        onlineStoreUrl\n" +
                "        ...collectionImage\n" +
                "\t\n" +
                " \t\t\t\n" +
                "        \n" +
                "      }\n" +
                "    }\n" +
                "  }\n" +
                "}\n" +
                "\n" +
                "fragment collectionImage on Collection{\n" +
                "  image{\n" +
                "    id\n" +
                "    originalSrc\n" +
                "    width\n" +
                "    height\n" +
                "  }\n" +
                "}");
        return queryRootExecutor.execWithBindValues(graphQLFullRequest, null).getCollections();
    }
```
So I think you are not supposed to define fragments in your schema file , they should work without it (could be wrong I am new)

Latsode
