### ISSUE TITLE
client_non_spring has a lot of Spring dependencies

### ISSUE THREAD

**Issue by mircea-cm** [graphql-java-generator/graphql-maven-plugin-project#108]
Hello,
I followed strictly the **client_non_spring** documentation and the generated client includes Spring Framework.
The generated classes that import org.springframework.* are:
- MutationExecutor
- QueryExecutor
- SpringConfiguration

**Comment by etienne-sf** [comment]
Yes, that's right. 

I know I have a work to on dependencies. But I have some stuff to finish before. 

Étienn

**Comment by etienne-sf** [comment]
I studied your comment. 

Based on these points:
* The future of this plugin is to be merged with the spring-graphql. I'll work on this soon.
* My (very personnal) opinion, is that using Spring is the best way to develop Java app. 
* It would be complex to have a client runtime without spring dependencies included (complex to separate and complex to test)

Based on these points, the Spring dependencies would still be included in future versions.

Etienne

**Comment by mircea-cm** [comment]
Thank you for fixing this.
My (very personal) opinion about Spring is completely different:
 - has a lot of magic inside - just adding spring-security dependency you'll have a very nice login page that you didn't need or implemented, also you'll have to override some stuff to get rid of it. 
 - was also kinda late to the reactive party, and from what I understood, you can't write both imperative and reactive. 
 - The artifacts are bigger and slower than some of their competition - https://www.baeldung.com/spring-boot-vs-quarkus
Kind regards,
Mircea C.
