### ISSUE TITLE
Feature request: configuration for the folder containing the .graphql file(s) - schemaFilePattern not enough / documentation not explicit enough?

### ISSUE THREAD

**Issue by abedeoan** [graphql-java-generator/graphql-maven-plugin-project#11]
At the moment, it seems that the plugin expects that the .graphql files are located in /src/main/resources/

Request: provide this folder as a configuration for the plugin. 

Use-case: the schema file(s) resides in a different artifact. So before executing the plugin we need to unpack it (usually in the project.build.outputDirectory).

**Comment by etienne-sf** [comment]
Hello,

Hum, it's a fair one. 

BTW, It's already possible.

Check the full doc for the plugin with this command:
mvn help:describe -Dplugin=graphql -Ddetail

With the schemaFilePattern you can put a path.

I didn't test, but try this value for schemaFilePattern in the pom :
../../../target/YourFolder/*.graphqls

The start of the path is still /src/main/resources/.
So ../../.. let's you at the root for your project.

Give it a try. If it works, I'll update the doc before closing this issue.

Etienne

**Comment by abedeoan** [comment]
Hi Etienne, 

I tried configuring the _**schemaFilePattern**_ to contain not only the file name pattern but also the relative path to the file - and indeed it has the desired effect. 
Personally I have a slight preference for using 2 different configuration parameters for this: one for the file name pattern and one for the folder path; or at least a different name for the parameter - if we keep this as just one setting. 
However if documentation is extended, I can agree to close the issue.

Thank you for your fast reply - as always!

Amelia

**Comment by abedeoan** [comment]
Hi Etienne, 

Any comment / suggestion on the issue encountered above?

Regards, 
Amelia

**Comment by etienne-sf** [comment]
Bobsel's PR is now merged. It will be available in the next release.

**Comment by etienne-sf** [comment]
Amelia,

  Can you confirm that the parameter _schemaFileFolder_  works like expected ?

If yes, can you close this issue ?

NB : the plugin doc is available here: 
https://graphql-maven-plugin-project.graphql-java-generator.com/graphql-maven-plugin/graphql-mojo.html

Etienne
