### ISSUE TITLE
Allow more pluggable QueryExector configurations

### ISSUE THREAD

**Issue by mjohnston-il** [graphql-java-generator/graphql-maven-plugin-project#110]
We're looking into using this library with Micronaut but it is a bit awkward to supply the Micronaut HttpClient implementation.  We've come up with a solution but we'd like a small modification to the QueryExecutor.java class.  Patch attached
[gql_generator.txt](https://github.com/graphql-java-generator/graphql-maven-plugin-project/files/7571891/gql_generator.txt)
.

**Comment by etienne-sf** [comment]
Yes, it seems harmful. And if it's useful, then it's a good one
:)

Can you provide it through a github push request ?

Etienne

**Comment by mjohnston-il** [comment]
https://github.com/graphql-java-generator/graphql-maven-plugin-project/pull/112

**Comment by etienne-sf** [comment]
It is available in the 1.18, that has just been released.

Etienne
