### ISSUE TITLE
Sub-objects are null when returned to Graphiql

### ISSUE THREAD

**Issue by TrueDub** [graphql-java-generator/graphql-maven-plugin-project#111]
I have an app that uses graphql-maven-plugin to provide a front-end for a REST service. 

When I gather the data and return the object generated by the plugin in the DataFetchersDelegateImpl class for the query, all relevant data is present. So the conversion using Dozer is working well.

However, when returned to the GraphiQL front-end, the two fields that are objects are null.

Am I missing something in the logic of how this works, or is there a step I'm not performing?

**Comment by etienne-sf** [comment]
What is the GraphQL query, that you execute ?

I guess that in graphiql, your request didn't ask for all the fields you want to see. 

Étienne

**Comment by TrueDub** [comment]
The query I execute is

```
{
  getReservation {
    xmlns
    xmlnsxsi
    xsischemaLocation
    Version
    Target
    PrimaryLangID
    TimeStamp
    VehRetResRsInfo {
      TPA_Extensions {
        VendorPictureURL
        IsFreesale
        Status
        CancellationPolicy
      }
    }
    VehRetResRsCore {
      VehReservation {
        Status
      }
    }
  } 
}
```

and the (redacted) response is:

```
{
  "data": {
    "getReservation": {
      "xmlns": "appropriate String1",
      "xmlnsxsi": "appropriate String2",
      "xsischemaLocation": "appropriate String3",
      "Version": "1.002",
      "Target": "Test",
      "PrimaryLangID": "EN",
      "TimeStamp": "2021-11-25T09:46:50.324Z",
      "VehRetResRsInfo": null,
      "VehRetResRsCore": null
    }
  }
}

```

The object returned from the `DataFetchersDeleteQueryImpl` class contains a value of "Confirmed" in the Status field of `VehReservation` in `VehRetResRsCore`

**Comment by etienne-sf** [comment]
From your request, `VehRetResRsInfo` and `VehRetResRsCore` are objects.

So you should have `VehRetResRsInfoDelegate` and `VehRetResRsCoreDelegate`  interfaces. The value returned by the query is the value returned by these data fetcher implementations.

The value for these fields returned in the `DataFetchersDeleteQueryImpl` is ignored by default.
You can probably check in the `VehRetResRsInfoDelegate` and `VehRetResRsCoreDelegate`  implementations if the source object contain this fields. In which case you can return them.

This is the way GraphQL works : it fetches one level, then recurse the next level. This prevents to fech useless data : your server implementation is done without knowing if your client request will query the `VehRetResRsInfo` and `VehRetResRsCore` or not.
So GraphQL take only into accounr the return of the  data fetcher implementations of these two fields. And more important: it will call them only if it's usefull, from the requests that has been received.

Etienne

**Comment by TrueDub** [comment]
Ah, I see - that is a fundamental misunderstanding on my part. 

Thank you for your explanation. I'll close this conversation as it's not an issue any longer.
