### ISSUE TITLE
Does the client generation not work with schema.json?

### ISSUE THREAD

**Issue by Sam-Kruglov** [graphql-java-generator/graphql-maven-plugin-project#113]
I couldn't find any info on whether I can use the [`schema.json`](https://www.apollographql.com/docs/android/essentials/get-started-java/#download-your-schemajson-file) for generating my client code. All the documentation asks for `.graphqls` files which is hand-written only, as it seems. I would like to re-generate my client as part of the CI to keep it up to date, so it will use the `schema.json` that is served by the deployed application.

This is the way the Apollo plugin works.
https://github.com/aoudiamoncef/apollo-client-maven-plugin
https://www.apollographql.com/docs/android/essentials/get-started-java/

**Comment by mheidt** [comment]
Have you tried renaming your schema.json into .graphqls and tried from there? When I generate my server, I use several
graphqls files and not a schema.json. Apollo seems to expect the graphql requests in graphqls files only.
In the end its all JSON...and graphql :)

**Comment by etienne-sf** [comment]
Hum, 

I see the point. 

The question is to take the result of an introspection query, without any change. 

So no, it doesn't work (yet). 

 But it's an interesting point. I'll check that. 

Étienne

**Comment by spyro2000** [comment]
Hi there, :) 

Yes, would be great if JSON could be supported as many APIs don't make their schema file available, so all you can do is a manual introspection. And this returns JSON...

**Comment by etienne-sf** [comment]
Hello,

Ok, thanks for this comment.
I'm working on the native compilation mode. I'll work on this one after.

Etienne

**Comment by etienne-sf** [comment]
Done in release 2.6
