### ISSUE TITLE
Interface with Interface field is not properly generated

### ISSUE THREAD

**Issue by DimaSol** [graphql-java-generator/graphql-maven-plugin-project#114]
Hi,
Consider the following schema:
```
interface IFoo {
    id: ID
    bar: IBar
}

interface IBar {
    id: ID
}

type TFoo implements IFoo {
    id: ID
    bar: TBar
}

type TBar implements IBar {
    id: ID
}
```

generation of the code is failing with the following exception: `error: TFoo is not abstract and does not override abstract method setBar(IBar) in IFoo
public class TFoo `

The reason is that while the IFoo interface defines a method `void setBar(IBar bar)` the TFoo type defines `void setBar(TBar bar)` that doesn't override the interface method.

I think generation should probably be something like (generic type should be added for each interface field in the type):
```
@GraphQLInterfaceType("IFoo")
public interface IFoo<I_BAR extends IBar>  {

	@GraphQLScalar(fieldName = "id", graphQLTypeSimpleName = "ID", javaClass = String.class)
	public void setId(String id);

	@GraphQLScalar(fieldName = "id", graphQLTypeSimpleName = "ID", javaClass = String.class)
	public String getId();

	@GraphQLNonScalar(fieldName = "bar", graphQLTypeSimpleName = "IBar", javaClass = IBar.class)
	public void setBar(I_BAR bar);

	@GraphQLNonScalar(fieldName = "bar", graphQLTypeSimpleName = "IBar", javaClass = IBar.class)
	public I_BAR getBar();
}

@GraphQLObjectType("TFoo")
public class TFoo 
	implements IFoo<TBar>{
...
}
```

I'd also expect the DataFetchersDelegate interfaces to inherit from each other in such cases:
```
public interface DataFetchersDelegateIFoo<I_BAR extends IBar> {
	public CompletableFuture<I_BAR> bar(DataFetchingEnvironment dataFetchingEnvironment, DataLoader<String, IBar> dataLoader, IFoo origin);
	public I_BAR bar(DataFetchingEnvironment dataFetchingEnvironment, IFoo origin);
	public List<? extends IFoo<I_BAR>> batchLoader(List<String> keys, BatchLoaderEnvironment environment);
}

public interface DataFetchersDelegateTFoo extends DataFetchersDelegateIFoo<TBar> {
// only additions fields in this specific type should exist in this interface
}
```

**Comment by etienne-sf** [comment]
Hello,

Are you sure that this schéma is valid ?

The spec is not precise on this point. But my opinion is that you must declare the exact same field in the concrete type than in the interface. 

So the bar's field of the TFoo type should be of type IBar. 


Étienne

**Comment by DimaSol** [comment]
Hi @etienne-sf ,
Thank you for the fast reply.

The spec is indeed missing a reference to this specific use case, but graphql-java library for example seems to support it and accepts this schema, idea lint accepts it as well as valid schema.
I've done a further check and modified the example to the following:
![image](https://user-images.githubusercontent.com/6746815/147727168-f5461e1a-c54f-4d2c-bd7f-2098effd97f6.png)
you can see that idea marks it as invalid because now TFoo does not implement IFoo as defined in spec but fixing it to:
![image](https://user-images.githubusercontent.com/6746815/147727218-368ec043-0d92-4d62-b28e-953c7ef10ebf.png)
also passes the validation because now TFoo does implement IFoo...

**Comment by DimaSol** [comment]
@etienne-sf further search in the web brought me to [this spec repo](https://github.com/graphql/graphql-spec/blob/main/spec/Section%203%20--%20Type%20System.md) that describes types validation and this use case looks like a valid one to me (see section 5 under `IsValidImplementation(type, implementedType)`):

```
**Type Validation**

Object types have the potential to be invalid if incorrectly defined. This set
of rules must be adhered to by every Object type in a GraphQL schema.

1. An Object type must define one or more fields.
2. For each field of an Object type:
   1. The field must have a unique name within that Object type;
      no two fields may share the same name.
   2. The field must not have a name which begins with the
      characters {"__"} (two underscores).
   3. The field must return a type where {IsOutputType(fieldType)} returns {true}.
   4. For each argument of the field:
      1. The argument must not have a name which begins with the
         characters {"__"} (two underscores).
      2. The argument must accept a type where {IsInputType(argumentType)}
         returns {true}.
3. An object type may declare that it implements one or more unique interfaces.
4. An object type must be a super-set of all interfaces it implements:
   1. Let this object type be {objectType}.
   2. For each interface declared implemented as {interfaceType},
      {IsValidImplementation(objectType, interfaceType)} must be {true}.

IsValidImplementation(type, implementedType):

   1. If {implementedType} declares it implements any interfaces,
      {type} must also declare it implements those interfaces.
   2. {type} must include a field of the same name for every field
      defined in {implementedType}.
      1. Let {field} be that named field on {type}.
      2. Let {implementedField} be that named field on {implementedType}.
      3. {field} must include an argument of the same name for every argument
         defined in {implementedField}.
         1. That named argument on {field} must accept the same type
            (invariant) as that named argument on {implementedField}.
      4. {field} may include additional arguments not defined in
         {implementedField}, but any additional argument must not be required,
         e.g. must not be of a non-nullable type.
      5. {field} must return a type which is equal to or a sub-type of
         (covariant) the return type of {implementedField} field's return type:
         1. Let {fieldType} be the return type of {field}.
         2. Let {implementedFieldType} be the return type of {implementedField}.
         3. {IsValidImplementationFieldType(fieldType, implementedFieldType)}
            must be {true}.

IsValidImplementationFieldType(fieldType, implementedFieldType):
  1. If {fieldType} is a Non-Null type:
     1. Let {nullableType} be the unwrapped nullable type of {fieldType}.
     2. Let {implementedNullableType} be the unwrapped nullable type
        of {implementedFieldType} if it is a Non-Null type, otherwise let it be
        {implementedFieldType} directly.
     3. Return {IsValidImplementationFieldType(nullableType, implementedNullableType)}.
  2. If {fieldType} is a List type and {implementedFieldType} is also a List type:
     1. Let {itemType} be the unwrapped item type of {fieldType}.
     2. Let {implementedItemType} be the unwrapped item type
        of {implementedFieldType}.
     3. Return {IsValidImplementationFieldType(itemType, implementedItemType)}.
  3. If {fieldType} is the same type as {implementedFieldType} then return {true}.
  4. If {fieldType} is an Object type and {implementedFieldType} is
     a Union type and {fieldType} is a possible type of {implementedFieldType}
     then return {true}.
  5. If {fieldType} is an Object or Interface type and {implementedFieldType}
     is an Interface type and {fieldType} declares it implements
     {implementedFieldType} then return {true}.
  6. Otherwise return {false}.
```

**Comment by etienne-sf** [comment]
Hello,

Yes this is pretty clear.

So the sample schema you provided is valid, and the generated code must be able to deal with it.

But the proposal you did for the generated code (with parameterized interfaces and types) is too complex. It is too different from the original GraphQL schema (I actually don't understand the value of the parameterized type). And furthermore, it would break existing code.

There is a simpler way to achieve compatilibty of the generated code.

The reason why it doesn't compile is only one missing method in the generated `TFoo` class: `void setBar(IBar bar)`.
So adding only this method in the generated code would do the trick:

```java
public class TFoo implements IFoo {

	String id;
	TBar bar;

	@Override
	public String getId() {
		return id;
	}

	@Override
	public void setId(String id) {
		this.id = id;
	}

	@Override
	public TBar getBar() {
		return bar;
	}

	/** This method makes the TFoo class be compatible with the IFoo interface */
	@Override
	public void setBar(IBar bar) {
		if (bar instanceof TBar)
			setBar((TBar) bar);
		else
			throw new IllegalArgumentException("bar must be an instanceof TBar (in TFoo.setBar(IBar)");
	}

	public void setBar(TBar bar) {
		this.bar = bar;
	}
}
```

What do you think about this ?

**Comment by DimaSol** [comment]
Hi @etienne-sf 
While your proposal will work as well IMHO doing it as I proposed is a bit cleaner and not requires multiple method to get same field... Making another getter feels a bit hacky to me and if I had to implement wiring by myself with no auto-generation I'd go with generics for this purpose. Why are you saying going with generics is very comple? maybe I can take part and assist with the implementation if you'll choose to go this direction...
Also, would be glad to know what do you think about the second part I mentioned - data loaders?

**Comment by etienne-sf** [comment]
I see several issues in your proposal.

1) It make the generate code more complex to use (so the user code would be more complex)

In you first sample, the IFoo java interface is parameterized. So every time someone uses it, he/she will have to precise parameterized type for this interface.
Why would have the developper have to define IFoo<Ibar>, where the type is just IFoo ?
I want the java code to be as simple as possible, and as near from the GraphQL schema as possible. And having to define a parameterized time, the is actually not necessary, generate useless complexity

2) TFoo is an instance of IFoo. But parameterized type are just a mess.

To store an instance of TFoo in a java IFoo variable, the standard code (based on the GraphQL schema) should be:
```java
IFoo ifoo = new TFoo();
```

It works smoothly with my proposal. 
But it generates a compilation warning with yours. It's not a big deal .. unless for people who changed the compilation configuration to make it an error. These people would not be able to use the code generated by the plugin


Then, the next code should be allowed, but won't compile:
```java
IFoo<IBar> ifoo = (IFoo<IBar>) new TFoo();
```

So there will be issues with a GraphQL type like this one:
```
type AnotherType {
	IFoo ifoo
}
```

The next code would not compile, whereas its just a basic need:
```java
public class AnotherType {
	IFoo<IBar> ifoo;

	public void setIfoo(IFoo<IBar> ifoo) {
		this.ifoo = ifoo;
	}
}
AnotherType anotherType = new AnotherType();
TFoo tfoo = new TFoo();
anotherType.setIfoo(tfoo); //This won't compile!!
```

To overcome this compilation error, one must write something like this:
```java
anotherType.setIfoo((IFoo<IBar>) (Object) tfoo);
```

Which is really ugly. And would be a good reason to not use the plugin.

3) Order pf parameterized type may change, depending on GraphQL schema changes

Your sample is the basic one. But what happends with an IFoo type that has several field which are instances of interfaces, like this:
```
interface IFoo1 {
    id: ID
    bar1: IBar1
    bar2: IBar2
    bar3: IBar3
    bar4: IBar4
}
```

The mapping java interface would be:
```java
public interface IFoo1 <I_BAR1 extends IBar, I_BAR2 extends IBar, I_BAR3 extends IBar, I_BAR4 extends IBar>{
    id: ID
    bar1: IBar1
    bar2: IBar2
    bar3: IBar3
    bar4: IBar4
}
```

And the order of the parameterized types may change, when the schema is changed. This would generare compilation errors in the user's code, or very tricky runtime errors.

**Comment by etienne-sf** [comment]
The 1.18.1 solves this issue, in the way I described here.
