### ISSUE TITLE
Generated server code for subscription not always follows schema definition

### ISSUE THREAD

**Issue by michelepra** [graphql-java-generator/graphql-maven-plugin-project#122]
Generated server code cannot allow send null value to subscription if in the schema the result of subscription is optional (mean null value is permitted) like `type Subscription {
    doSubscription: String
}` 

To allow send null value to publisher the generated server code interface must be `Publisher<Optional<[javaType]>>` and not `Publisher<[javaType]>` because in reactive stream we cannot [call onNext with null value](https://github.com/reactive-streams/reactive-streams-jvm#2-subscriber-code) that it _MUST throw a java.lang.NullPointerException to the caller_ .
 
Default implementation of graphql-java use [value unboxer](https://github.com/graphql-java/graphql-java/blob/7bac61e56ef765f168a53fcca1a7121543ce66a5/src/main/java/graphql/GraphQL.java#L212) that unwrap java.util.Optional with [wrapped](https://github.com/graphql-java/graphql-java/blob/7bac61e56ef765f168a53fcca1a7121543ce66a5/src/main/java/graphql/execution/DefaultValueUnboxer.java#L27) value out of the box.

It is easy to achieve this by modifying the related template

**Comment by etienne-sf** [comment]
Thank you Michele,

I'll make sure that I have an Integration test that test this before accepting the PR.
This integration should fail, and then become successfull once I merge your PR.

Currently, all the subscriptions used in IT tests always return values. So I hadn't seen this issue.

Etienne

**Comment by etienne-sf** [comment]
Hello, I just release the 1.18.2, which contains this correction

Thanks
Etienne
