### ISSUE TITLE
IllegalArgumentException is thrown from setters of fields when using builder and there are fields not set.

### ISSUE THREAD

**Issue by DimaSol** [graphql-java-generator/graphql-maven-plugin-project#124]
I'm using a builder to create some object and if I haven't set some field, when builder#build is going over all fields to create the object, in case field is null, it is failing in the instanceof check.

**Comment by etienne-sf** [comment]
Hello,

I used these builder a lot in the JUnit tests. And I generally use only some fields. I never got this error.

Can you provide some more info ?

**Comment by DimaSol** [comment]
Hi @etienne-sf , this is a result of upgrading to 1.18.2 version when using a pojo that is implementing an interface.
In this case, the field setter code is checking if the value type is an instanceof the one that is expected to be in the interface implementing class and since null is not an instanceof the expected type, it arrives to this code:
`
throw new IllegalArgumentException("The given <field name> should be an instance of String, but is an instance of "
					+ id.getClass().getName());
`
this is a result of https://github.com/graphql-java-generator/graphql-maven-plugin-project/issues/114 changes

**Comment by etienne-sf** [comment]
Right, I see
:(

That's a big bug. Easy to correct, but big.
I'll deliver a correction very soon.

**Comment by etienne-sf** [comment]
Can you check the 1.18.3 version, that I just released?

Etienne

**Comment by DimaSol** [comment]
Sure, will check and update

**Comment by DimaSol** [comment]
Issue is fixed, thank you!
