### ISSUE TITLE
Support for Multiple Schemas, Multiple GraphQL Servers

### ISSUE THREAD

**Issue by hmolinari-attentive** [graphql-java-generator/graphql-maven-plugin-project#126]
Is there any chance that the graphql-java-generator maven plugin will be able to generate classes for a list of schemas?  For example, generate classes for schema A, put in package M, put in folder X, generate classes for schema B, put in package N, put in folder Y, etc.

**Comment by hmolinari-attentive** [comment]
In the case that my application (spring or not) needs to communicate with the GraphQL APIs of multiple providers

**Comment by etienne-sf** [comment]
RTFM

This is already possible. 
Check this page : https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/client_more_than_one_graphql_servers
