### ISSUE TITLE
Are custom scalars respected in client?

### ISSUE THREAD

**Issue by DimaSol** [graphql-java-generator/graphql-maven-plugin-project#127]
Hi,
I'm getting some json serialization issue because it looks custom scalars are not respected when executing a request.
Please consider the following use case:

build.gradle:
```gradle
dependencies {
    implementation 'com.graphql-java:graphql-java-extended-scalars:17.0'
}

generateClientCodeConf {
    // some properties...
    customScalars = [ [
        graphQLTypeName: "DateTime",
        javaType: "java.time.OffsetDateTime",
        graphQLScalarTypeStaticField: "graphql.scalars.datetime.DateTimeScalar.INSTANCE"
    ]
}
```
where `graphql.scalars.datetime.DateTimeScalar.INSTANCE` is taken from `com.graphql-java:graphql-java-extended-scalars:17.0` dependency.

schema.graphqls:
```gql
scalar DateTime

extend type Mutation {
    fooMu(data: BarInput!): FooRes
}

input BarInput {
    barTime: DateTime
}
```

code:
```java
private final QueryExecutor queryExecutor;

public callFooMu(String query) {
    gqlMutation = queryExecutor.getGraphQLRequest(query);

    BarInput input = BarInput.builder()
        .withBarTime(OffsetDateTime.now())
        .build();

    Query result = gqlMutation.execMutation(
        "data", input
    );
}
```

execution of the above code is resulted with `com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type "java.time.OffsetDateTime" not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.HashMap["variables"]->java.util.HashMap["data"]->package.of.bar.BarInput["barTime"])`

stack trace:
```stacktrace
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type "java.time.OffsetDateTime" not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.HashMap["variables"]->java.util.HashMap["data"]->package.of.bar.BarInput["barTime"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1276)
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3742)
	at com.graphql_java_generator.client.GraphQLObjectMapper.writeValueAsString(GraphQLObjectMapper.java:261)
	at com.graphql_java_generator.client.RequestExecutionSpringReactiveImpl.execute(RequestExecutionSpringReactiveImpl.java:163)
	at com.graphql_java_generator.client.request.AbstractGraphQLRequest.exec(AbstractGraphQLRequest.java:439)
```

I've started with trying to add the `com.fasterxml.jackson.datatype.jsr310.JavaTimeModule` to the GraphQLRequest object mapper but found out that the request object mapper is not very accessible from the outside and is being created for each and every invocation (which IMHO is not very efficient) but then it hit me that the custom scalar is the one to handle this type and not the object mapper at all, right? Any thoughts?

**Comment by etienne-sf** [comment]
In this case, Jackson should not handle the mapping 'itself'. The mapping should be delegated to the custom scalar. I'll add a DateTime type in the JUnit tests to check that.

Some comments about your post:
* The object mapper in the `GraphQLRequest` type is created in the `AbstractGraphQLRequest` class. It is static, and thus it's created only once.
* The `DateTimeScalar` should be accessed through the `ExtendedScalars`

Etienne

**Comment by DimaSol** [comment]
@etienne-sf from what I see in code, the static instance of the object mapper is never used, instead getGraphQLObjectMapper method is called during execution which is creating new instance of GraphQLObjectMapper that creates new object mapper in the constructor, am I missing something?

**Comment by etienne-sf** [comment]
Hello,

I added a DateTime scalar in the JUnit tests, and had no such issue : I added a DateTime field in an input type, and checked that the value given in the input data is returned by the server (so the client and the server generated by the plugin can both read and write OffsetDateTime values).

It may depend on the Java version. For these tests, I use an openJDK 13.

Etienne

NB: About the creation of the Object Mapper, you're right. I had to call my old memory about this one ! :) Actually, the mapper must take into account the GaphQL aliases in Queries, Mutations and Subscriptions. As the aliases are specific to each request, the mapper needs to be recreated each time. It would be possible to keep the same Jackson ObjectMapper, and only recreate the GraphQLObjectMapper. I added that to the TODO list. But I think it's only a tiny optimisation.

**Comment by etienne-sf** [comment]
Then, about the `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` module: I think that adding it as a dependency of your project is enough : https://geowarin.com/correctly-handle-jsr-310-java-8-dates-with-jackson/

**Comment by etienne-sf** [comment]
Any news on this ?

**Comment by etienne-sf** [comment]
I can't find these exceptions. I searched on the console output, and in the allGraphQLCases server's log.

Then, I'm "worried" about the question you asked:
> If you can guide me of how to make the entire project build (with tests)

Does it means the project has errir during the build, with your configuration?

Or perhaps, as you're apparently using Gradle, the issue is to use in a Gradle build the result of a local plugin's Maven build?

**Comment by etienne-sf** [comment]
If it's the last point, I updated the "howto build the project" wiki page:

https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/internal_howto_build

**Comment by DimaSol** [comment]
Have you tried running it when passing the input as a parameter? I think it is failing when trying to parse the parameter json when used like this:
```gql
mutation fooMu(
    $data: BarInput!
) {
    fooMu(data: $data) {
        ...<FooRes fragment goes here>
    }
}
```
re failing build, I'm trying to run the maven project and have failing tests, after commenting failed tests, others are failing as well for wrong expected values...
```
[ERROR] Tests run: 17, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.196 s <<< FAILURE! - in com.graphql_java_generator.util.GraphqlUtilsTest
[ERROR] com.graphql_java_generator.util.GraphqlUtilsTest.test_getArgument_forum  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalArgumentException: Unknown schema: The CustomScalarRegistry for the '' schema has not been defined
	at com.graphql_java_generator.util.GraphqlUtilsTest.test_getArgument_forum(GraphqlUtilsTest.java:157)
[ERROR] com.graphql_java_generator.util.GraphqlUtilsTest.test_getArgument_CustomScalar  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalArgumentException: Unknown schema: The CustomScalarRegistry for the '' schema has not been defined
	at com.graphql_java_generator.util.GraphqlUtilsTest.test_getArgument_CustomScalar(GraphqlUtilsTest.java:283)
[ERROR] com.graphql_java_generator.util.GraphqlUtilsTest.test_getArguments_list  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: Unknown schema: The CustomScalarRegistry for the '' schema has not been defined
	at com.graphql_java_generator.util.GraphqlUtilsTest.test_getArguments_list(GraphqlUtilsTest.java:430)
[ERROR] com.graphql_java_generator.util.GraphqlUtilsTest.test_getArgument_serverMode_UUIDID  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: Unknown schema: The CustomScalarRegistry for the '' schema has not been defined
	at com.graphql_java_generator.util.GraphqlUtilsTest.test_getArgument_serverMode_UUIDID(GraphqlUtilsTest.java:206)
[ERROR] com.graphql_java_generator.util.GraphqlUtilsTest.test_getArgument_ListOfInputTypes  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: Unknown schema: The CustomScalarRegistry for the '' schema has not been defined
	at com.graphql_java_generator.util.GraphqlUtilsTest.test_getArgument_ListOfInputTypes(GraphqlUtilsTest.java:367)
[ERROR] com.graphql_java_generator.util.GraphqlUtilsTest.test_getArgument_serverMode_StringID  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalArgumentException: Unknown schema: The CustomScalarRegistry for the '' schema has not been defined
	at com.graphql_java_generator.util.GraphqlUtilsTest.test_getArgument_serverMode_StringID(GraphqlUtilsTest.java:261)
```

**Comment by etienne-sf** [comment]
Hello,

The error you have here has no link with custom scalars. It's relative to the plugin's configuration for the tests.

Did you change anything in the project, before building it ?

Etienne

**Comment by DimaSol** [comment]
I never claimed that error is because of custom scalars :)
Anyway, I changed nothing in the project...

**Comment by etienne-sf** [comment]
So there is a difference. 

Can you precise what you've done exactly?
And what is your Java version? OS?

**Comment by DimaSol** [comment]
I've ran maven install.
I believe the following is the information you are asking for:
```
/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java -Dmaven.multiModuleProjectDirectory=/Users/dimasolomonov/workspace/graphql-maven-plugin-project -Dmaven.home=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3 -Dclassworlds.conf=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven-event-listener.jar -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=59561:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds.license:/Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar org.codehaus.classworlds.Launcher -Didea.version=2021.2.2 --debug --errors --update-snapshots clean
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Applications/IntelliJ IDEA.app/Contents/plugins/maven/lib/maven3
Java version: 11.0.12, vendor: Eclipse Foundation, runtime: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
Default locale: en_IL, platform encoding: UTF-8
OS name: "mac os x", version: "11.2", arch: "x86_64", family: "mac"
```
Also, have you had a chance to check my latest reply re the issue itself?

**Comment by etienne-sf** [comment]
I tested with a JDK temurin 11.0.4 (on widows) and had no issues with the scalar integration tests.

I guess something is wrong with your project or environment configuration. 

But as I can't repeat this issue, I can' correct it. 


Can you provide me with a full sample that triggers this issue ?

**Comment by DimaSol** [comment]
Looks like not reproducing anymore with latest version.
