### ISSUE TITLE
Trouble with generated code

### ISSUE THREAD

**Issue by Liliandev** [graphql-java-generator/graphql-maven-plugin-project#128]
Hello,

I have a Client type in a GraphQL Schema and when i use plugin to generate graphql's client, plugin use javax.ws.rs.client.Client and not the Client's type generated

Is there a tip to achieve ?

Many Thanks

**Comment by etienne-sf** [comment]
Can you provide some more information, there ?

I understand that there is a mismatch between the Client class coming from the GraphQL schema and the `javax.ws.rs.client.Client` class.
But where does it occur ? 
In the plugin's code ? If yes, where exactly ?
In your code ?

Etienne

**Comment by Liliandev** [comment]
Here is the schema
![image](https://user-images.githubusercontent.com/4364899/157626842-1de7eba0-7b59-4f0a-ac62-7373a2abc5c1.png)

![image](https://user-images.githubusercontent.com/4364899/157627005-d976323c-a661-4dd9-9aef-cf0c76af6adf.png)

Generated code by maven's plugin : 

![image](https://user-images.githubusercontent.com/4364899/157627189-404061b8-d532-4549-aac1-6c6eaed7b290.png)

but the Client Type imported is the javax.ws.rs.client.Client type and not the Client Type from my graphql's schema

![image](https://user-images.githubusercontent.com/4364899/157627418-46e55708-9391-42ba-9650-83a7a5b5a9a0.png)

**Comment by etienne-sf** [comment]
Yes, I see.

There is currently no easy way to correct that.
You can override the templates that generates the code (you'll need to override two templates, see #125 for more information on this).
I'll correct that, to remove the import of `javax.ws.rs.client.Client`. So a correction will be available in the next version.

Etienne

**Comment by Liliandev** [comment]
Thanks for your help !

**Comment by Liliandev** [comment]
Thanks for fixing code, do you have a deadline to create new release ?

Many thanks for you help !

**Comment by etienne-sf** [comment]
It should be some days, one week max

I have two other issues I'm working on

**Comment by Liliandev** [comment]
Many thanks,

I saw the new tag and tried with it but doesn't work, same as before.

Many Thanks

**Comment by etienne-sf** [comment]
That is strange : my integration test contains a `Client`, and I did repeat the issue, then correct it.

Can you double check that you're using the 1.18.4 plugin's version ?
And show me the generated code that is wrong ?

**Comment by Liliandev** [comment]
Sorry, my bad, i updated the runtime but forget the generator. All is ok, thanks for you great help !
