### ISSUE TITLE
generate client code using graphql schemas located in jar dependency

### ISSUE THREAD

**Issue by gpr7700** [graphql-java-generator/graphql-maven-plugin-project#129]
Hello

We are using the plugin and we are generating the client code for multiple functional domains. Each domain having its own folder under resources but it implies to copy/paste schemas between multiple projects

Is it possible to configure the plugin so that it uses the graphql schemas located in a jar dependency ?

Regards

Gregory

**Comment by etienne-sf** [comment]
To do this, you currently need to unzip the jar (typically in the target or buid folder), and use the `schemaFileFolder` parameter to indicate to the plugin where the GraphQL schema are.
More info on the [plugin doc page](https://graphql-maven-plugin-project.graphql-java-generator.com/graphql-maven-plugin/generateClientCode-mojo.html).

To unzip the jar, you can use the plugin [Apache Maven Dependency Plugin](https://maven.apache.org/plugins/maven-dependency-plugin/index.html), in its [dependency:unpack](https://maven.apache.org/plugins/maven-dependency-plugin/unpack-mojo.html)

Etienne
