### ISSUE TITLE
[Minor] Unnecessary import in the client generated code

### ISSUE THREAD

**Issue by abedeoan** [graphql-java-generator/graphql-maven-plugin-project#13]
In release 1.3.1 of the plugin, it seems that the client generated code imports exception org.springframework.boot.json.JsonParseException in CustomScalarDeserializer* classes. However this exception is not needed, so I assume it can be safely removed from template client_jackson_deserialize.vm.java?

**Comment by DirkMahler** [comment]
Will be solved as part of the PR for #15.
