### ISSUE TITLE
Supporting gql client autoconfiguration for spring boot version 2.7.x

### ISSUE THREAD

**Issue by DimaSol** [graphql-java-generator/graphql-maven-plugin-project#134]
Hi,
Is there a plan to support spring boot autoconfiguration as documented at [this documentation](https://docs.spring.io/spring-boot/docs/2.7.x/reference/htmlsingle/#features.developing-auto-configuration)?
Relevant spring ticket can be found [here](https://github.com/spring-projects/spring-boot/issues/29872)

**Comment by etienne-sf** [comment]
Hello

There is already an auto configuration file, that is generated, when in client mode. 

It's not clear to me about what enhancement this would add to the project. 

Can you show me what issue the current auto configuration class raises, that would be solved by that ?

Étienne

**Comment by DimaSol** [comment]
It will add support for spring boot versions > 2.7.x as the file name changes and should now be called org.springframework.boot.autoconfigure.AutoConfiguration.imports

**Comment by etienne-sf** [comment]
That is a very good point!
:)

I'll work on this one, then spring GraphQL

**Comment by etienne-sf** [comment]
Hum, I've read to quickly.

As this annotation will be available only from Spring Boot 2.7, I can't integrate it now: it would make mandatory the use of Spring Boot 2.7 (or above), with the relecant Spring Framework version.

This can break existing project that can't use these Spring versions.

So I won't implement it now.

Etienne

**Comment by DimaSol** [comment]
I'm think both files can be always generated and shouldn't disturb each other
