### ISSUE TITLE
Use Jetty instead of Netty as HttpClient

### ISSUE THREAD

**Issue by siamzam** [graphql-java-generator/graphql-maven-plugin-project#137]
Hi,

I want to replace Netty with Jetty. To do that I need to replace the code in these two files:
- SpringConfiguration.java
- com.graphql_java_generator.client.GraphQLConfiguration.java

For SpringConfiguration.java I can change the template. But how should I do this for GraphQLConfiguration.java?

**Comment by etienne-sf** [comment]
Hello,

This is a complex question, as there are many ways to use the plugin.
Are you using it as a Spring app ? If not, then the Client is a jetty one. But then, you can't use SSL nor web sockets. And this support will probably be removed in the 2.X releases.
Are you using subscriptions ? If yes, then netty is mandatory, I think. 


Can you be more specific about your usage of the plugin ?
Can you explain why you need to get rif of netty ?

Etienne

**Comment by siamzam** [comment]
I am using this plugin in a Spring app. I have to use Jetty because of another dependency in the project that only allows use of Jetty. No, I am not using subscriptions.

**Comment by etienne-sf** [comment]
As you stated, there is nothing ready to change netty to jetty. 
And frankly, I'm about to leave the jetty support in the 2.x branch 

Can you precise the way you use the plug-in ?

Here is what I guessed :
- you're using it to build a GraphQL client
- you've override the HttpClient bean with your own. 
- then there is an issue because of jetty versus netty.  

Is this correct ?
Do you have a code sample, so that I can start from that ?

Étienne

**Comment by etienne-sf** [comment]
I analysed it another time : it's quite complex to update the `GraphQLConfiguration` class, as it is largely used.

The easiest way for you, is probably to fork the project, and change that on your own version of it.

**Comment by siamzam** [comment]
> As you stated, there is nothing ready to change netty to jetty. And frankly, I'm about to leave the jetty support in the 2.x branch
> 
> Can you precise the way you use the plug-in ?
> 
> Here is what I guessed :
> 
> * you're using it to build a GraphQL client
> * you've override the HttpClient bean with your own.
> * then there is an issue because of jetty versus netty.
> 
> Is this correct ? Do you have a code sample, so that I can start from that ?
> 
> Étienne

Your guess is absolutely right.
Can't we use a template to do it?

**Comment by etienne-sf** [comment]
No: it's quite a particular need. 
I had to "leave" jetty, as I couldn't do all what I needed with it. 

I'm working on the 2.x version. It will be based on the spring-graphql project. And I'm not sure of the support that this project has on jetty. What's for sure, is that the plugin's code will be unaware of this "technical details". I think jetty will be supported. 

Étienne
