### ISSUE TITLE
Compilation Failures, keywords used in AutoGen

### ISSUE THREAD

**Issue by Jacrispys** [graphql-java-generator/graphql-maven-plugin-project#139]
While trying to build a very basic project that just prints from a repo... I got a slew of errors on compile, and notice that most of the errors are due to the AutoGen creating things with keywords as names, for example "new" as a enum constant, or "package" as a method name
![image](https://user-images.githubusercontent.com/69219325/174525562-d635a494-e7f2-44c8-9c2a-a874210035a6.png)
![image](https://user-images.githubusercontent.com/69219325/174525641-ce1e5013-17a7-4f63-b8ff-56ab43b3524d.png)

**Comment by etienne-sf** [comment]
Can you provide the GraphQL schema ?

That is strange, because a thought the Java names would be protected. 
Perhaps not in enum values.
I'll check that.  

Etienne

**Comment by Jacrispys** [comment]
Unfortunately I cannot provide a schema at this point in time, due to the project being in closed beta, however I can tell you that a variable is called 'package' which messes up the code gen as well.

**Comment by etienne-sf** [comment]
There was quite a re-work, with some side effects.

It's now solved, and available in the 1.18.7 release
