### ISSUE TITLE
Missing support for introspection "keywords" e.g. __typename in object response

### ISSUE THREAD

**Issue by abedeoan** [graphql-java-generator/graphql-maven-plugin-project#14]
Hello Etienne, 

I have a simple structure like below: 
type Query {
      getJobs(
        filter: _JobFilter
    ): [Job!]!
}

type Job {
    id: ID!
    startTime: Long!
    endTime: Long!
}

I am trying to format the response of this query as below: 
{
  getJobs(filter: {
    startTime_gt: 0
    ....
  })
{  id
   __typename
}
which behaves as expected in GraphQL Playground.
But in client mode, I have the below issue: 

com.graphql_java_generator.exception.GraphQLRequestPreparationException: The GraphQL type <Job> has no field of name <__typename>
	at com.graphql_java_generator.client.GraphqlClientUtils.checkFieldOfGraphQLType(GraphqlClientUtils.java:272)
	at com.graphql_java_generator.client.request.Builder.withField(Builder.java:413)
	at com.graphql_java_generator.client.request.Builder.withQueryField(Builder.java:665)
	at com.graphql_java_generator.client.request.Builder.withQueryResponseDef(Builder.java:602)

Please advise.

Regards,
Amelia

**Comment by etienne-sf** [comment]
Hello,

I released the 1.4 version that allows introspection on client side:
See: https://graphql-maven-plugin-project.graphql-java-generator.com/introspection.html

But apparently you want to mix introspection types within a "regular" GraphQL query.

Can you provide me a sample, or better, a server URL against which I can test that ?

Etienne

**Comment by etienne-sf** [comment]
Yep, Ok, I tested it on my side.
On the allGraphQLCases client sample: the query "{allFieldCases {id __typename}}" works perfectly with graphiql.

Hum, hum... I'll have to release an 1.4.1 soon, I fear...

**Comment by etienne-sf** [comment]
You can test the reading of __typename : it's now available on the master branch.

Please note that there is a code impact. 
Previously, the plugin would generate a concrete class for each interface. This is no longer the case: thanks to this feature request, it points me out how to know the real class of a returned object. So the deserialization of the response is now correct : the correct classes are created.

Can you give it a try ?

**Comment by abedeoan** [comment]
Hi Etienne, 

Thank you for the update! We'll give this a try in the upcoming weeks. 
Is this already part of a released version or only on the snapshot version?

Regards, 
Amelia

**Comment by etienne-sf** [comment]
It's currently only the snapshot, and will be released soon

**Comment by etienne-sf** [comment]
I released the 1.5.0 yesterday. 

Can you confirm that this issue is solved ?
