### ISSUE TITLE
Use graphqls in a dependency

### ISSUE THREAD

**Issue by tbeauvais-imagine** [graphql-java-generator/graphql-maven-plugin-project#141]
The separation of the server and client is important.

How can we include a dependency on a JAR that includes a graphqls file in the classes in order to generate the client model?

**Comment by etienne-sf** [comment]
I don't understand you question. 

What's the real issue ?
Is your app both a GraphQL server and a GraphQL client ?
Or something else ?

Étienne

**Comment by tbeauvais-imagine** [comment]
Thanks for the speedy response.

I have a JAR with the graphqls, I would like to load that from the classpath. How can I configure the plugin to take that JAR and graphqls?

**Comment by etienne-sf** [comment]
Yes

Please read the answer for the issue #129.

I'll add an entry in the FAQ, for this one.
