### ISSUE TITLE
Documentation structure not sound

### ISSUE THREAD

**Issue by chrberSTO** [graphql-java-generator/graphql-maven-plugin-project#144]
Either I am too stupid to understand your documentation or the documentation is badly written. Let's find out ;)

This is what I am using: https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/client_non_spring

... because for the moment I do not wish to use Spring even though I might run into trouble with authentication later.

First there is the header: Use the Spring capabilities with a non spring app

then it states to read [Use the Spring capabilities with a non-spring App](https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/client_faq#use-the-spring-capabilities-with-a-non-spring-app).

But below there is the header: Creating a GraphQL client app

It is just really confusing the way the documentation is structured.

I have managed to create the resources using the 

graphql:generateClientCode goal, but after having the added the sources to the compile path using the plugin I get loads of errors that it can not find imported resources like package com.graphql_java_generator.client.request does not exist

Please help, because I am utterly lost in your documentation. I want to get to being able to execute queries without the use of Spring. Do you have an example that just works? Which you have checked that it works?

It would be nice to have documentation that states:

1. do this
2. then this
3. then this
4. and now it should all work.

Your documentation is more like:

1. Do this
2. jump here
3. do that
4. come back to documentation for 1. 
5. read and do not know whether this is part of the non spring or spring app scenario

Thank you.
Kind regards.
Christian

**Comment by etienne-sf** [comment]
My understanding is that you've tried to use the plug-in without spring, and for compilation errors. 


My recommandation: Start with the tutoriels. 

Once it compiles, switch to a non-spring app if you wish, by following the 'non-spring app' wiki page. 

Étienne
