### ISSUE TITLE
Continue of discussion re issue 140

### ISSUE THREAD

**Issue by DimaSol** [graphql-java-generator/graphql-maven-plugin-project#145]
Please check my comment at https://github.com/graphql-java-generator/graphql-maven-plugin-project/issues/140

**Comment by etienne-sf** [comment]
Follow up for issue #140:

Based on this schema:

```graphql
type Query {
    foo: Foo
}

interface IBar {
    name: String
}

interface I2Bar implements IBar {
    name: String
}

type Bar implements I2Bar & IBar {
    name: String
}

interface IFoo {
    bar: IBar
}

interface I2Foo implements IFoo {
    bar: I2Bar
}

type Foo implements I2Foo & IFoo {
    bar: Bar
}
```

The plugin generates:
```java
	public interface IFoo {
		public void setBar(IBar bar);
	}

	public interface I2Foo extends IFoo {
		public void setBar(I2Bar bar);
	}
```

Once this is generated,  Java class that inherits from I2Foo must implements **both** setters, like this:
```java
	public class Foo implements I2Foo, IFoo {
		@Override
		public void setBar(IBar bar) {
			// TODO Auto-generated method stub
		}

		@Override
		public void setBar(I2Bar bar) {
			// TODO Auto-generated method stub
		}
	}
```

This is a java constraint.

In your proposal, the Foo class should have only the `setBar(IBar bar)`. 
I can not accept this: this setter allows invalid data to be created (if setBar is called with a non-I2Bar instance). My strong opinion is that the generated code **_must_** stick to the GraphQL schema. So, if only one setter exists, it must be the `setBar(I2Bar bar)`. 

And, as you've making me thinking about it, I found a way to avoid it: having a default implementation for the `setBar(IBar bar)` method in the generated `I2Foo` interface:


```java
	public interface IBar {
		public void setName(String name);
	}

	public interface I2Bar extends IBar {
		@Override
		public void setName(String name);
	}

	public class Bar implements I2Bar {
		@Override
		public void setName(String name) {
			// TODO Auto-generated method stub
		}
	}

	public interface IFoo {
		public void setBar(IBar bar);
	}

	public interface I2Foo extends IFoo {
		@Override
		default public void setBar(IBar bar) {
			if (bar == null || bar instanceof I2Bar) {
				setBar((I2Bar) bar);
			}
			throw new IllegalArgumentException(
					"The 'bar' parameter should be an instance of 'I2Bar', but is an instance of '"
							+ bar.getClass().getName() + "'");
		}

		public void setBar(I2Bar bar);
	}

	public class Foo implements I2Foo, IFoo {
		@Override
		public void setBar(I2Bar bar) {
			// TODO Auto-generated method stub
		}
	}
```

I'll see to integrate it in a next release.

Etienne

**Comment by DimaSol** [comment]
Not sure how much I agree with the issue of allowing invalid data to be created as there is a validation within the setter implementation re the type of the value being set same as done in the generated code now, also, nothing prevents from the programmer to invoke wrong setter in currently generated code as well. 
Furthermore, while I do agree generated code should reflect the schema as much as possible, I don't think setters in the interfaces are required to achieve it but only getters are enough because schema defines what fields of (interface) type you can get(!) and the setters can be generated only on the real type...
In a more complex structure, when one want a more grained control of the types, if one chooses to implement interfaces with his own types (instead of using the generated pojos), setters might be totally redundant for him in case the type holds some more complex data structure (not necessarily reflected in schema at all) and getters can return some aggregated / computed data on top of the data in the pojo, consider the following (simplified) example:

```java
	public interface IBar {
		// redundant
		public void setName(String name);

		// this is the only thing really defined in the gql schema
		public String getName()
	}

	public interface I2Bar extends IBar {
		// redundant
		@Override
		public void setName(String name);

		// this is the only thing really defined in the gql schema
		public String getName()
	}

	public class MyCustomNotGeneratedBar implements I2Bar {
		String firstName;
		String lastName;

		// redundant because firstName & lastName was somehow populated with pojo creation
		@Override
		public void setName(String name) {
			// TODO Auto-generated method stub
		}

		public String getName() {
			return firstName + " " + lastName;
		}
	}
```

**Comment by etienne-sf** [comment]
I disagree here.

The issue is not just to mark that the interface possesses one attribute. It's also to allow standard use cases.
And **_the setter is one of the two standard methods for a property_**. The generated code must have it.

For instance, with this star wars schema:

```graphql
interface characters {
  id: String!
  name: String!
}

query {
  characters: [Character]
}

mutation {
  updateCharacters(c: Character): Character
  updateCharacter(c: [Character!]!): Character
}
```

A normal use is to retrieve the character's list, update the name (or whatever other property), then update them back on the server.
