### ISSUE TITLE
Feature request: use an abstraction e.g. SLF4J for logging

### ISSUE THREAD

**Issue by abedeoan** [graphql-java-generator/graphql-maven-plugin-project#15]
In version 1.3.1 of the plugin, the generated code has an explicit dependency on LOG4J, which is forcing the clients to use a specific logging framework (which is not ideal).

So our proposal is bind the generated code with the SLF4J API,thus allowing the client to use their preferred logging library ( be it log4j, the Java logging API, or another).

Some online references on this topic: 
https://howtodoinjava.com/log4j/slf4j-vs-log4j-which-one-is-better/
https://javapapers.com/java/slf4j-vs-log4j/

Note: if you agree with this proposal, we can also prepare a pull request. 

Regards, 
Amelia

**Comment by etienne-sf** [comment]
Of course I agree with that. 
And of course, I ´ll be happy to integrate a pull request from you. 
🙂

**Comment by DirkMahler** [comment]
Preparing a PR for this.

**Comment by abedeoan** [comment]
This issue can be closed now.
