### ISSUE TITLE
Support for BigDecimal and Long Custom Scalar Types

### ISSUE THREAD

**Issue by klvnnsrikanth** [graphql-java-generator/graphql-maven-plugin-project#159]
Hi, is there any idea on when support will be added for BigDecimal and Long data types?

**Comment by etienne-sf** [comment]
Hello,

BigDecimal and Long data types are already supported. As they are non-standard GraphQL type, they are support via Custom Scalars. Check [this page](https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/usage_customscalars) of the doc for information about this.

Etienne

**Comment by klvnnsrikanth** [comment]
Got it thanks
