### ISSUE TITLE
we’re not using spring but we need to add a custom header to the http requests. how do we do that?

### ISSUE THREAD

**Issue by Camerino** [graphql-java-generator/graphql-maven-plugin-project#160]
I wand to add a custom header to the GraphyQL request. From the Generated code, the header is being set only in the execute method and it is not accepting any custom header from request. I see some solutions to this in spring but we are not using spring. How should I do that in this situaiton?

**Comment by etienne-sf** [comment]
Hello,

Can you precise the version of the plugin that you're using ?
Then, [this answer in the FAQ](https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/client_faq#use-the-spring-capabilities-with-a-non-spring-app) may answer your question.

Etienne
