### ISSUE TITLE
Not support VARIABLE_DEFINITION

### ISSUE THREAD

**Issue by caojiaqi123** [graphql-java-generator/graphql-maven-plugin-project#162]
we define some directive, such as 
directive @NotBlank(message: String = "NotBlank.message") on VARIABLE_DEFINITION | ARGUMENT_DEFINITION,
but now it do not support **ARGUMENT_DEFINITION** type

**Comment by etienne-sf** [comment]
Hello,

Your message is really unclear.

I guess that you've done a upgrade of the plugin's version, which causes this issue.
Correct ?
From which version to which one ?

Then, what means 'it do not support ARGUMENT_DEFINITION type' ? Is there any error message displayed ?

Etienne

**Comment by etienne-sf** [comment]
Hello,

Can you precise what you're expecting from the plugin there ?

Etienne

**Comment by etienne-sf** [comment]
Released in the 1.18.9.
