### ISSUE TITLE
StringBuffer, modernizer-maven-plugin fails

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#163]
Hello Etienne,

I upgrade my project to a new version that is using the moderniser-maven-plugin now.
It complains, that the generated code in 
GraphQLServerMain and GraphqlUtils is using StringBuffer and that StringBuilder should be preferred.

Could you change that please?

Regards,
Markus

**Comment by etienne-sf** [comment]
The change all command is wonderful
:)

It will be available in the next release.

**Comment by etienne-sf** [comment]
Released in the 1.18.9.
