### ISSUE TITLE
Add descriptions for input parameters if they exist (Complement #164)

### ISSUE THREAD

**Issue by dpalmmna** [graphql-java-generator/graphql-maven-plugin-project#167]
After correction of #164 the descriptions for input parameters are not used. 

Proposed to add the descriptions if they exist.

Joined proposed code modifications to add these descriptions. 

graphql-maven-plugin-logic\src\main\java\com\graphql_java_generator\plugin\DocumentParser.java
graphql-maven-plugin-logic\src\main\resources\templates\client_query_mutation_executor.vm.java
graphql-maven-plugin-logic\src\main\resources\templates\client_subscription_executor.vm.java
[proposed-modifications.zip](https://github.com/graphql-java-generator/graphql-maven-plugin-project/files/10246208/proposed-modifications.zip)

**Comment by etienne-sf** [comment]
I'll check that.
If you've done the code modification, can you do a Pull Request on github for that ?
It would be easier for me to check the changes.


Etienne

**Comment by etienne-sf** [comment]
Released in the 1.18.10 version
