### ISSUE TITLE
different configurations for individual schema schema files

### ISSUE THREAD

**Issue by johannoikonomou** [graphql-java-generator/graphql-maven-plugin-project#178]
Hi!

I'd like to define different configurations (especially ```packageName```) for specific schema files. I tried defining multiple executions with different ```schemaFileFolder``` configs (i also tried playing around with ```schemaFilePattern```) to differentiate between schema files. However after the 1st execution the plugin always says: 

```The GraphQL schema file(s) is(are) older than the generated code. The code generation is skipped.```

There is the ```skipGenerationIfSchemaHasNotChanged``` parameter but i believe it's deprecated. 

Is there a way to achieve my desired behavior - full disclosure i'm a maven newbie... 

Thanks!

**Comment by etienne-sf** [comment]
Hello,

You should take a look at this [pom.xml](https://github.com/graphql-java-generator/graphql-maven-plugin-project/blob/master/graphql-maven-plugin-samples/graphql-maven-plugin-samples-allGraphQLCases-client/pom.xml) file. It contains three executions, with different target folders and package names. 

The issue you encounter, is that the files are all generated in the same target folder. So, starting from the second execution, the plug-in thinks the files have already been generated. 

Please note that you should use the ´springBeanSuffix´ parameter, to make it work properly. This allows to properly differentiate the spring beans. 

Étienne

**Comment by johannoikonomou** [comment]
That makes sense, i'll check out the example. Thank you very much @etienne-sf

**Comment by johannoikonomou** [comment]
it works :)
