### ISSUE TITLE
Allowing Authorization Token in Connection_Init payload for subscription

### ISSUE THREAD

**Issue by bhowmikdebarshi** [graphql-java-generator/graphql-maven-plugin-project#185]
Hi

Currently we are allowing to pass the token in header while establishing the subscription channel. Can we allow it in connection_init payload though some sort of interceptor?  
https://docs.spring.io/spring-graphql/docs/current-SNAPSHOT/reference/html/#client.websocketgraphqlclient.interceptor 

Thanks

**Comment by etienne-sf** [comment]
Which version of the plug-in are you using?
For a client or a server?

If you're using a 1.x version, the no, there is no easy way. But you can change the runtime, for instance by copying it into your project, and change its behavior. Of course, you would then have to do it again each time you upgrade the plug-in. 

As you're pointing out the spring-GraphQL doc, I guess you switched to the 2.0Rc1. 

Then I don't know. But if spring-graphql allows it, juste do it. You'll have to check their doc. 

Étienne

**Comment by etienne-sf** [comment]
Please let me know what you've found (or will find) : 
* If spring provides such an interceptor, I'll document it
* If spring doesn't provide it, then I'll document it.

**Comment by etienne-sf** [comment]
Any news ?
