### ISSUE TITLE
Spring 6 - missing createError() method in OAuthTokenExtractor.GetOAuthTokenClientResponse implementing spring reactive ClientResponse

### ISSUE THREAD

**Issue by capdav** [graphql-java-generator/graphql-maven-plugin-project#189]
Hello Etienne, 

Seems there is an issue with what is generated for Spring 6 in 
public static class GetOAuthTokenClientResponse implements ClientResponse

We have the following exception:
com.graphql_java_generator.client.OAuthTokenExtractor.GetOAuthTokenClientResponse is not abstract and does not override abstract method <T>createError() in org.springframework.web.reactive.function.client.ClientResponse

Do you confirm?

Thanks,
DAvid

**Comment by etienne-sf** [comment]
I confirm I encountered it. But I thought it was solved.
I'll check that.

Are you using the 2.0 version of the plugin ?

Etienne

**Comment by capdav** [comment]
Ok thanks for the confirmation ;-)

Yes, we are using the 2.0 version

**Comment by etienne-sf** [comment]
Hello,

I added the oauth2 capability to the forum sample (provided in the maven plug-in project).
It works. 

Are you using the ´OAuthTokenExtractor´ class from a copy/paste, or from the plug-in runtime ?

Étienne

**Comment by etienne-sf** [comment]
If you set the plug-in parameter ´copyRuntimeSources´ to false (which is its default value), then it works!

This method is not used. So this issue occurs if the code is compiled with a spring framework 6 version. And the runtime is currently compiled against a 5.c version. 

It will be solved in the next version. 

Étienne

**Comment by etienne-sf** [comment]
Solved in the 2.1 release

**Comment by capdav** [comment]
Great! Thanks a lot Etienne..
Sorry for my late reply
