### ISSUE TITLE
Documentation site gone?

### ISSUE THREAD

**Issue by rogieroudshoorn** [graphql-java-generator/graphql-maven-plugin-project#191]
Hi,

I've love to read up on the maven plugin goals, but it seems https://graphql-maven-plugin-project.graphql-java-generator.com/ has disappeared. Is there any place to read up?

Regards,

Rogier

**Comment by etienne-sf** [comment]
Thanks for the report. 
It's now corrected.

I missed the domain renewal email, due to a misconfigurationsomwhere...  
:(
