### ISSUE TITLE
how bind graphQl respone with implement java class

### ISSUE THREAD

**Issue by superchenwei** [graphql-java-generator/graphql-maven-plugin-project#194]
Hi 
  I'm using com.graphql-java-generator 1.18.11 client mode,here is the issue,client generate code function is ok,but when I'm testing the below code
            _org.datahub.client.BrowseResults searchResults = queryExecutor.browse(
                "{start count total entities{urn name}}",input
            );_
   got error 
   _The GraphQL type 'Entity' (org.datahub.client.Entity) has no field of name 'name'_

 Below is the filed  'entities' defination in class 'BrowseResults' 
	_@JsonProperty("entities")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListEntity.class)
	@GraphQLNonScalar( fieldName = "entities", graphQLTypeSimpleName = "Entity", javaClass = org.datahub.client.Entity.class, listDepth = 1)
	List<org.datahub.client.Entity> entities;_

org.datahub.client.Entity is a interface,there is a java class Dataset with field 'name' implement from Entity,how cloud I let the 'browse ' method know should use Dataset class bind GraphQl response but not org.datahub.client.Entity.
  
                                                                                                                                                                                           Thanks!

**Comment by etienne-sf** [comment]
Hello,

Can you copy the definition of the `Entity` GraphQL interface here ? Does it actually contain a `name` field ?

Etienne
