### ISSUE TITLE
master will not compile on JDK8

### ISSUE THREAD

**Issue by paulmchugh777** [graphql-java-generator/graphql-maven-plugin-project#20]
Current master branch will not compile on JDK8 because of use of Class.getPackageName() in class Builder.

Class.getPackageName() came in in JDK9.

Using Class.getPackage().getName() will make backwards compatible to JDK8.

**Comment by abedeoan** [comment]
I am having the same issue right now, when trying to upgrade from 1.3.1 to 1.3.2. 
When can we expect a fix & a new release?

**Comment by paulmchugh777** [comment]
Hi Etienne,

Did you seem my PR re the JDK8 compile failure?

https://github.com/graphql-java-generator/graphql-maven-plugin-project/pull/21

Would it be possible to get this merged?

Also, when is it likely that 1.4-SNAPSHOT will be released and available for download?

Best regards

Paul

**Comment by graphql-java-generator** [comment]
I just merged it.
I release a new version soon : I added introspection capability.

**Comment by etienne-sf** [comment]
The 1.4 version has been released.

It should be Ok

I can't use directly the JDK 8 for "internal" reasons, and I thought that setting the source and target java version to 1.8 as enough...  :(

**Comment by paulmchugh777** [comment]
Hi Etienne,

Thanks very much for doing the release. We are now using it successfully.

Paul
