### ISSUE TITLE
queries on multiple endpoints on the same server

### ISSUE THREAD

**Issue by avmr48shadow** [graphql-java-generator/graphql-maven-plugin-project#201]
Hi,

I use the client generator to query 3 things.
The problem is, they are exposed on 3 different endpoints on the server.

I use a @GraphQLRepository which is really great.

Do you know a workaround to be able to attach each method to a specific endpoint.
I've tried some things but nothing elegant.

Thank you very much.

**Comment by avmr48shadow** [comment]
I've seen this page : https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/client_more_than_one_graphql_servers

I have a probleme with that : 

the different endpoints share some common schema alos

**Comment by etienne-sf** [comment]
Hello,

This link should answer your question: https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/client_graphql_repository#using-graphql-repositories-with-spring-against-several-graphql-servers


The idea is, when you define a GraphQLRepository, is that one GraphQLRepository can query only one GraphQL server. 
So, as you have three such servers, you must have three GraphQLRepositories. 

Étienne
