### ISSUE TITLE
Declare plugin thread safe

### ISSUE THREAD

**Issue by cyrilc-pro** [graphql-java-generator/graphql-maven-plugin-project#208]
When using Maven parallel builds, Maven reports the following warning:
```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but this         *
[WARNING] * project contains the following plugin(s) that have goals not  *
[WARNING] * marked as thread-safe to support parallel execution.          *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked as thread-safe in .....:
[WARNING]   com.graphql-java-generator:graphql-maven-plugin:1.18.12
[WARNING]
[WARNING] Enable debug to see precisely which goals are not marked as thread-safe.
[WARNING] *****************************************************************
```

(Note: I'm using plugin 1.18.12 because I'm stuck with an old Spring Boot version.)

My guess is that the plugin is actually thread-safe and just needs to be declared as thread-safe.

See example here: https://github.com/quarkusio/quarkus/issues/27596

**Comment by etienne-sf** [comment]
Hello,

Yes, marking a plugin as thread safe is quite easy.
But insuring it to be thread safe is really complex : the plugin uses several libraries, which themselves use libraries... I have no way to guaranty that all these dependencies are thread safe.
BTW, after a quick check, I see nothing that could cause threading issues.

How important is it for you ?

Etienne

**Comment by cyrilc-pro** [comment]
It is definitely not a blocker.
I'm aware of the complexity of thread-safety checks.
I guess that you might just acknowledge that the plugin "must" be thread-safe, mark it as such, and then, if one day someone finds an issue with parallel builds, you'll "just" process it as any other issue (fix it or not).
You could even rollback the adoption of the thread-safety flag ;)

**Comment by etienne-sf** [comment]
Done in release 2.6
