### ISSUE TITLE
Not able to generate pojo for 2 graphql endpoint in a project 

### ISSUE THREAD

**Issue by soumyarsamal** [graphql-java-generator/graphql-maven-plugin-project#212]
Hi Team, 
We tried generating POJO for two graphql endpoint in a single project, we are able to generate pojo but it is creating duplicate class names under folder target/generated-sources/graphql-java-generator which is failing on compile time

duplicate classes are of folder(annotations, customscaler,execption,server.Util,util)

-> we tried generating both endpoint POJO on a single folder but it is only generating for the first task under execution tag

Question: how to not generate com.graphQl_java_generator folder for second schema 

Below we have mentioned our pom.xml and attached screenshot for reference 

Please help us resolving our issue 

![WhatsApp Image 2024-06-04 at 12 05 22 PM](https://github.com/graphql-java-generator/graphql-maven-plugin-project/assets/83507063/b5f81681-af1c-465f-968c-a51ea71a5fd3)

‹plugin>
‹groupId>com.graphql-java-generator</groupId> «artifactId>graphql-maven-plugin</artifactId>
«version>1.17.3‹/version>
‹executions>
‹execution>
<id>cam</id>
‹configuration>
«targetSourceFolder>target/generated-sources/graphql-naven-plugin/can</targetsourceFolder>
«schemaFileFolder>src/test/resources/gql/files/cam/</schemaFileFolder>
‹generateJPAAnnotation>false‹/generateJPAAnnotation>
«schemaFilePattern>*.graphql</schemaFilePattern>
«separateUtilityClasses>trues/separateUtilityclasses>
‹packageName>model.gql.cam</packageName>
«generateDeprecatedRequestResponse>false</generateDeprecatedRequestResponse>
‹mode>server</mode>
«skipGenerationIfSchemaHasNotChanged>false</skipGenerationIfSchemaHasNotChanged>
<addRelayConnections>true</addRelayConnections>
</configuration>
‹goals>
‹goal-generatePojo</goal>
</goals>
‹/execution> sexecution>
<id>gl</id>
«configuration>
< targetSourceFolder»target/generated-sources/graphql-maven-plugin/gl</targetsourceFolder»
«SChemaFileFolder>src/test/resources/gql/g/${environment}/</schemaFiLeFoLder»
«generateJPAAnnotation>false</generateJPAAnnotation>
«schemaFilePattern>*.graphql</schemaFilePattern>
«separateUtilityClasses>trues/separateutilityCLasses>
‹packageName>model.gql.gl≤/packageName>
«generateDeprecatedRequestResponse>false‹/generateDeprecatedRequestResponse>
‹mode>server</mode>
«skipGenerationIfSchemaHasNotChanged>false</skipGenerationIfSchemaHasNotChanged>
caddRelayConnections>true‹/addRelayConnections>
</configuration>
‹goals>
‹goal>generatePojo</goal>
</ goals>
‹/execution>
</executions>
</plugin>
<plugin>

@mjohnston-il , @DirkMahler @gonzalogomezgarcia  @johanngoltz  @johanngoltz

**Comment by Alehandroalex** [comment]
I faced the same issue when trying to use second schema

**Comment by etienne-sf** [comment]
Hello,

Did you check the [dqdq](https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/client_more_than_one_graphql_servers) doc ?

The two important things to manage, here are:
* Provide a separate `targetSourceFolder` for at least one schema, so that the generated code for your two GraphQL schema are generated in different folders
* Provide a `springBeanSuffix` for at least one of the schemas (but it's more readable to provide one for each)

In the provided conf, the first condition is met, but not the second one.

Etienne

**Comment by soumyarsamal** [comment]
Hello Etienne, 

Thanks for your response.

We have a non spring application, so springBeanSuffix is of no use 

We have already provided targetSourceFolder but due to duplicate class names under com.graphql_java_generator we are getting compilation error (please refer above screenshot)


Is there any way we resolve this issue ?

**Comment by etienne-sf** [comment]
Hello,

I think you have no choice here, but use `springBeanSuffix`, and  what's described [in this page](https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/client_non_spring)
