### ISSUE TITLE
Cannot use custom Controllers without implementing default delegates

### ISSUE THREAD

**Issue by Vojtech-Sassmann** [graphql-java-generator/graphql-maven-plugin-project#215]
Since version 2.5, there is a `DataFetchersDelegateRegistry` class which requires all generated delegates. This prevents defining a custom controller with a custom implementation.

**Comment by etienne-sf** [comment]
Can you provide here yous custom implementation ?
Like stated [in the wiki](https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/server_migrate_1-x_to_2-x#override-the-generated-spring-entity-controller), your custom controller must override the default one.

Please note that this may be related to the #214 issue, on which I'm working.

Etienne

**Comment by Vojtech-Sassmann** [comment]
> Can you provide here yous custom implementation ? Like stated [in the wiki](https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/server_migrate_1-x_to_2-x#override-the-generated-spring-entity-controller), your custom controller must override the default one.
> 
> Please note that this may be related to the #214 issue, on which I'm working.
> 
> Etienne

Sure thing!

For example, with this schema:
```graphql
type Foo {
    id: ID!
    name: String
}

extend type Query {
    foo(id: ID!): Foo
}
```

The library generates the following classes:

* `FooController`
* `DataFetchersDelegateFoo`
* `DataFetchersDelegateRegistry`

However, we have a use case when the methods in the `DataFetchersDelegateFoo` are not sufficient. (Eg. to fetch some related entities, we want to use DataLoader. But the library doesn't know this, because we are not using the `ID` in this one situation like we do for all other entities.)

Therefore, we wanted to implement our own custom `FooController`. We did it like so:

```Java
@Controller
@SchemaMapping(typeName = "Foo")
public class FooController
{
   // custom methods
}
```

And this worked until version 2.5 where a new class `DataFetchersDelegateRegistry` is generated. This class also requires the `DataFetchersDelegateFoo`. Because of that, we must provide a dummy implementation of this interface which does nothing. 

> Like stated ... your custom controller must override the default one.

Does this mean that this use case is not supported? As you have mentioned, the custom controller MUST override the default one?

**Comment by etienne-sf** [comment]
Hello,

I've read your message several time, but I'm not quite sure of the issue you encounter.

What I understand is that it should work with this dummy implementation of the `DataFetchersDelegateFoo` and the overrided controller that extends the FooController class.

Can you precise the error you get with this configuration ?
(dummy implementation of the `DataFetchersDelegateFoo` and the overrided controller that extends the FooController class)

Etienne

**Comment by Vojtech-Sassmann** [comment]
> Hello,
> 
> I've read your message several time, but I'm not quite sure of the issue you encounter.
> 
> What I understand is that it should work with this dummy implementation of the `DataFetchersDelegateFoo` and the overrided controller that extends the FooController class.
> 
> Can you precise the error you get with this configuration ?
> (dummy implementation of the `DataFetchersDelegateFoo` and the overrided controller that extends the FooController class)
> 
> Etienne

I'm sorry for such confusing description of the problem.

The problem is that I don't like the dummy implementation of the `DataFetchersDelegateFoo`. I would prefer not having to write it. 

Shouldn't be the `DataFetchersDelegateFoo` not required in the `DataFetchersDelegateRegistry` ?

**Comment by Vojtech-Sassmann** [comment]
Hi @etienne-sf sorry for such a late response.

I'm just looking at your proposed solutions, and I'm not sure if I can imagine it as a whole, but solution no. 4 could make sense to me.

Also, I was thinking about one other solution - marking the delegates as optional in the `DataFetchersDelegateRegistry`. Wouldn't it solve the problem? 

```java
@Autowired(required = false)
DataFetchersDelegateFoo dataFetchersDelegateFoo;
```

**Comment by etienne-sf** [comment]
Nice, another idea!
:) 

But it would not solve the #214 issue, which needs to prevent some controllers to not be generated.
So I already added a parameter to prevent some (or all) controllers and their datafetcher delegates to not being generated.

**Comment by etienne-sf** [comment]
The `ignoredSpringMappings` has been added in the 2.8 release
