### ISSUE TITLE
Capitalization issue in QueryController with generated code.

### ISSUE THREAD

**Issue by gottschd** [graphql-java-generator/graphql-maven-plugin-project#217]
Hello,

I want to support an external available graphql schema with this `graphql-java-generator`.

Given the (simplified) schema example below with a Query definition that begins with an _uppercase_ letter:
```
type MyDataObject {
  email: String
  uuid: ID!
  version: Int!
}

input MyDataObjectWhereUniqueInput {
  email: String
}

type Query {
  MyDataObjectFindUnique(where: MyDataObjectWhereUniqueInput!): MyDataObject!
}
``` 
GraphQL Java Generator maven plugin generates a `DataFetchersDelegateQuery` interface with a _lowercase_ method name 
```
public com.acme.MyDataObject myDataObjectFindUnique(
			DataFetchingEnvironment dataFetchingEnvironment,
			com.acme.MyDataObjectWhereUniqueInput where);
```
However, the generated `QueryController` expects an _uppercase_ variant of the interface's method in the `DataFetchersDelegateQuery`.
```
	public Object MyDataObjectFindUnique(DataFetchingEnvironment dataFetchingEnvironment, 
			@Argument("where") com.acme.MyDataObjectWhereUniqueInput where) {
                // Compile error - cannot find symbol: the method in the interface begins with a lower case .
 		return  this.dataFetchersDelegateQuery.MyDataObjectFindUnique(dataFetchingEnvironment , where); 
	}
```
I'm using spring boot `3.3.1` and the version of the graphql-java-server-runtime is `2.7`. 
The outcome is a compile error when generating the server code.

Am i missing something?

Kind regards,
Danny

**Comment by etienne-sf** [comment]
Hello,

You missed nothing.

[GraphQL good practice](https://www.apollographql.com/docs/technotes/TN0002-schema-naming-conventions/#casing) is that  field names start with lower case letters.
It respected so much, that you're the first to encounter this issue.

It's actually a bug of the plugin.

I'll correct it in the next version.

Etienne

**Comment by gottschd** [comment]
Hello Etienne,

thanks for both, the link and the bugfix.

Much appreciated!

Danny
