### ISSUE TITLE
passing user auth token to GraphQL request

### ISSUE THREAD

**Issue by mng77** [graphql-java-generator/graphql-maven-plugin-project#222]
Hi,
Is there a v2 update on issue 105? I need to do something similar but haven't managed to build the correct code and am going round in circles.   I can see overriding the WebClient  bean and having a filter within that would be the thing to do but this line - at least in the code I using from the v2 runtime dependency, _GraphQLConfiguration.getWebClient_ doesn't exist.  Any help appreciated!

thanks
-mark

**Comment by etienne-sf** [comment]
Hello,

Did you check this wiki page: https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/client_oauth2 ?

**Comment by mng77** [comment]
Hi, Yes, ended up looking at that and what others have done.  Finally resolved which is great. Have pasted the code for the Filter below in case anyone else needs the same, key bit being getting hold of the HttpServletRequest so you can get at the auth header in that.

thanks.


`@Component
public class AuthTokenExchangeFilter implements ExchangeFilterFunction {

    private static Logger logger = LoggerFactory.getLogger(AuthTokenExchangeFilter.class);

    public final static String AUTHORIZATION_HEADER_NAME = "Authorization";

    @Override
    public Mono<ClientResponse> filter(ClientRequest request, ExchangeFunction next) {
		
		ServletRequestAttributes attributes = (ServletRequestAttributes) RequestContextHolder.getRequestAttributes();
        if (attributes == null) {
            return Mono.error(new IllegalStateException("No request attributes available"));
        }

        HttpServletRequest httpServletRequest = attributes.getRequest();

        // Extract the Authorization header from HttpServletRequest
        String authorizationHeaderValue = httpServletRequest.getHeader(AUTHORIZATION_HEADER_NAME);

        if (authorizationHeaderValue == null ) {
            logger.error("WARNING: No " + AUTHORIZATION_HEADER_NAME + " header found, when exactly 1 is expected");
        } 
		
		ClientRequest newRequest = ClientRequest.from(request)
		.header(AUTHORIZATION_HEADER_NAME, authorizationHeaderValue)
		.build();

		return next.exchange(newRequest);
          
	}


}`
