### ISSUE TITLE
Unable to use custom scalar types as input parameter of a query

### ISSUE THREAD

**Issue by igorng** [graphql-java-generator/graphql-maven-plugin-project#26]
Hello,

I defined a custom scalar n my shema, but I am unable to use it as quary parameter:

**Schema**

`scalar Object

type Customer  {
  refId : String
  birthDate : String
}

type Query {
    find(client: Object): [Customer]
}
schema {
  query: Query
}
`
_Object_ here should be ser / deser as a map, and I used GraphQLScalarType.newScalar() builder to implement the scalar type ser / deser, using Jackon Object mapper.

When I try to fire a query, the serialiazed string of the Object map passed as a param to the query seems to be the result of Map.toString() instead of the json form of the map that should have been issued by the jackson mapper deser.

Am I missing something here?

Thank you.

**Comment by abedeoan** [comment]
Hi Igor, 

Any particular reason for declaring your "Object" as a scalar? 

I assume that what you need is an input type - see here an interesting thread on input types and where to use them: https://stackoverflow.com/questions/41743253/whats-the-point-of-input-type-in-graphql

And input types are for sure supported by the plugin - it's a feature I requested a few months ago, it was delivered by Etienne and tested by my team :) 

Good luck!
Amelia

**Comment by igorng** [comment]
Hi @abedeoan ,

In fact the Customer type has too many fields (about 80, and maybe more later), and we want to allow filtering on all the fields. Therefore, if we use the graphql input concept, we will have to define the input with 80 and more fields. As graphql do not allow using Type as input, we choose to let the client pass in a map of field / value that will be parsed on server side for filtering.

(sorry for the poor english :) )

**Comment by etienne-sf** [comment]
Hello,

Please give a try at the snapshot version. It should correct this issue.
I'm updating the documentation, and I will release it soon.

**Comment by etienne-sf** [comment]
I released the 1.5.0 yesterday. 

Can you confirm that this issue is solved ?
