### ISSUE TITLE
Quality Feature Request: Setup Build Pipeline

### ISSUE THREAD

**Issue by Bobsel** [graphql-java-generator/graphql-maven-plugin-project#34]
Setup a build pipeline for example on https://travis-ci.org/ .

* PR's requires a green build before they can merged to master
* no changes on master without a pr
* master should always have a green build

**Comment by etienne-sf** [comment]
OK, thank you also for the separated thread.

And yes, if you can help there, as you proposed, it would be nice.
:)

**Comment by etienne-sf** [comment]
This will done in the future, perhaps
