### ISSUE TITLE
Support for @connection directive

### ISSUE THREAD

**Issue by csplrj** [graphql-java-generator/graphql-maven-plugin-project#39]
I need @connection for relay as mentioned in this document
https://graphql-java-kickstart.com/tools/relay/
These directives is needed to detect changes as it changes output.
but graphql-maven-plugin-project does not works on such schema files?

**Comment by etienne-sf** [comment]
The graphql-maven-plugin should be able to manage it. 
But it's not embedded by default.

On the page you've given, I didn't found any word about the @connection.

Can you provide some more hints on this ?

Etienne

**Comment by csplrj** [comment]
The below code is mentioned in the url https://graphql-java-kickstart.com/tools/relay/ which shows @connection as tags

```
type Query {
    users(first: Int, after: String): UserConnection @connection(for: "User")
    organizations(first: Int, after: String): OrganizationConnection @connection(for: "Organization")
}

type User {
    id: ID!
    name: String
}

type Organization {
    id: ID!
}
```

**Comment by etienne-sf** [comment]
Hello,

  Relay adds its own directive and structure. But I was not able to find its GraphQL schema definition yet.

I'll properly integrate it as soon as I find it, or someone give a way to integrate it.

In the meantime, you can add this line into your GraphQL schema. 

directive @connection(for: String) on FIELD_DEFINITION

Etienne

**Comment by Kars-de-Jong** [comment]
What this directive basically does is replace a lot of boiler plate.

For the example above, it will generate the following extra GraphQL types:
```graphql
type UserConnection {
    edges: [UserEdge]
    pageInfo: PageInfo
}

type UserEdge {
    cursor: String
    node: User
}

type OrganizationConnection {
    edges: [OrganizationEdge]
    pageInfo: PageInfo
}

type OrganizationEdge {
    cursor: String
    node: Organization
}

type PageInfo {
  hasPreviousPage: Boolean!
  hasNextPage: Boolean!
}
```
Each type that is used as ``node`` needs to have an ``id`` field of type ``ID!``.
We implemented this in our schema as an interface to make it explicit:
```graphql
# Interface used by the Relay Connector Specification.
interface Node {
    id: ID!
}

type Organization implements Node {
  id: ID!
}
```

So, just adding the extra ``directive`` to the schema is not enough (it still complains about the missing ``xxxConnection``  types).

**Comment by Kars-de-Jong** [comment]
The relay connection specification can be found here: [GraphQL Cursor Connections Specification](https://relay.dev/graphql/connections.htm).

**Comment by etienne-sf** [comment]
I advanced a lot on this. It's almost ready.

I still need to add some integration tests, there.

**Comment by dchappelle** [comment]
Any word on this?.. I have run into the same issue.

**Comment by etienne-sf** [comment]
Hello,

I'm expecting that you're in client mode.

It's commited and available.

You'll find more information here: https://graphql-maven-plugin-project.graphql-java-generator.com/client_add_relay_connection.html

If you're in server mode, you can check: https://graphql-maven-plugin-project.graphql-java-generator.com/server_add_relay_connection.html


Etienne
