### ISSUE TITLE
How do I specify the implementation for a custom scalar type?

### ISSUE THREAD

**Issue by sbilello** [graphql-java-generator/graphql-maven-plugin-project#40]
`Failed to execute goal com.graphql-java-generator:graphql-maven-plugin:1.6.0:graphql (default-cli) on project next-client: The plugin configuration must provide an implementation for the Custom Scalar 'Long'.` 
https://github.com/graphql-java-kickstart/graphql-spring-boot/wiki/Creating-a-custom-scalar-type

**Comment by sbilello** [comment]
https://github.com/graphql-java-generator/graphql-maven-plugin-project/blob/master/graphql-maven-plugin-samples/graphql-maven-plugin-samples-Forum-client/pom.xml#L27-L33
I found an example over there but it looks like that this project is not really maintained as well as the apollo-graphql-client

**Comment by etienne-sf** [comment]
Hello,
Your starting question is about this plugin, but the link you gave is about graphql-java-kickstart.
So it's unclear to me if your last comment is about this plugin or about graphql-java-kickstart.

BTW, the error message states that you should provide the Custom Scalar implementation in the pom, like you've seen in the sample.

You'l find all the information on the plugin's site, on this page: https://graphql-maven-plugin-project.graphql-java-generator.com/customscalars.html

Etienne
