### ISSUE TITLE
How to use variables in filter parameter

### ISSUE THREAD

**Issue by avalakusuma** [graphql-java-generator/graphql-maven-plugin-project#41]
I am using GraphQLRequest(graphql-java-generator API)  for running GraphQL queries. I have trouble understanding on how to pass parameters in filters(I can pass first and offset as params but not filter params)
Could you please provide an example of how to pass filters with parameters. My example graphql query I am working on is as follows. 

{
  allMtColumns(first: ?, offset: ?, filter: {
      and: {
        mtEntityByEntityId: {
          mtSchemaBySchemaId: {
            name: { equalTo: ?schema}
            mtDatabasisByDatabaseId: { name: { equalTo: ?database } }
          }
        }
      }}) {
    edges {
      node {
        name
        id
        mtEntityByEntityId {
          id
          name
          mtSchemaBySchemaId {
            id
            name
            cqName
            type
            mtDatabasisByDatabaseId {
              id
              name
            }
          }
          cqName
        }
        entityId
        cqName
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
  }
}

**Comment by etienne-sf** [comment]
Hum,

It's quite hard to reply without the GraphQL schema.

AFAIU:
* allMtColumns is a query, that has three parameters: first, offset and filter.
* filter is an InputType
Right ?


So the plugin should have generated:
* A query type from the Query object in your GraphQL schema. I'll name it Query, here below.
* This Query class should contain a getAllMtColumnsGraphQLRequest method that allows you to prepare a Partial Request for the allMtColumns query.
* This Query class should contain a allMtColumns method to execute this query 


It would look to something like this:


GraphQLRequest allMtColumnsRequest;

void setup() {          
	// Create the Partial GraphQL request
	// This below will execute: allMtColumns(first:?first, offset: ?offset, filter: ?filter) { edges [...] startCursor } }
	allMtColumnsRequest = queryType.getAllMtColumnsGraphQLRequest("{ edges { node { name id mtEntityByEntityId { id name mtSchemaBySchemaId { id name cqName type mtDatabasisByDatabaseId { id name } } cqName } entityId cqName } } pageInfo { endCursor hasNextPage hasPreviousPage startCursor } }");
}

void exec() {
	first = 0;
	offset = 100;
	filter = new Filter(...);
	
	
	List<MtColumns> mtColumns = queryType.allMtColumns(allMtColumnsRequest, first, offset, filter);

	// Do something with mtColumns
	...
}





You can also use a Full request like this:



GraphQLRequest allMtColumnsRequest;

void setup() {          
	// Create the Full GraphQL request
	// This below will execute: allMtColumns(first:?first, offset: ?offset, filter: ?filter) { edges [...] startCursor } }
	allMtColumnsRequest = new GraphQLRequest("{allMtColumns(first:?first, offset: ?offset, filter: ?filter) { edges { node { name id mtEntityByEntityId { id name mtSchemaBySchemaId { id name cqName type mtDatabasisByDatabaseId { id name } } cqName } entityId cqName } } pageInfo { endCursor hasNextPage hasPreviousPage startCursor } }}");
}

void exec() {
	first = 0;
	offset = 100;
	filter = new Filter(...);
	
	
	List<MtColumns> mtColumns = allMtColumnsRequest.execQuery(first, offset, filter).getAllMtColumns;

	// Do something with mtColumns
	...
}



Hope this helps.

If not, can you provide me the GraphQL schema, so that I answer with a working response ?

Etienne

**Comment by avalakusuma** [comment]
Hi Etienne,

Thanks for your response. I am a beginner to use this GraphQLRequest API. 

I need help in preparing filter with variables so that I can send any values when I run. 

I provided schema, query, and GraphQLRequest code I am trying to test.
Could you please correct the GraphQLRequest code so that I will be able to pass filter with variables.

I would provide a simple schema with just 2 properties

schema
-------
entity{
id
name
}


SQL query
-------------
 select id, name from entities where id=1

Postgraphile query with filter
------
query filterQuery {
  allEntities(filter: {id: {equalTo: "1"}}) {
    edges {
      node {
        name
        id
      }
    }
  }
}

query with id as variable so I can pass any value in params
------
query filterQuery {
  allEntities(filter: {id: {equalTo: ?id}}) {
    edges {
      node {
        name
        id
      }
    }
  }
}

GraphQLRequest code I am trying
---------

fun filterQuery(idValue: Int){
var params = HashMap<String, Any>()
params.put("id", idValue)
val request = GraphQLRequest("{ allEntities(filter: {id: {equalTo: ?id}}) {
    edges {
      node {
        name
        id
      }
    }
  }
}")
 var response =request.execQuery(params).getAllEntities()
    print(response)
}

**Comment by etienne-sf** [comment]
Hello, 

The issue is on this line :

> val request = GraphQLRequest("{ allEntities(filter: {id: {equalTo: ?id}}) {
> ...

The whole filter should be in a bind variable.
Si it would be something like:

> fun filterQuery(idValue: Int){
> var filter = ...
> var params = HashMap<String, Any>()
> params.put("filter", filter)
> val request = GraphQLRequest("{ allEntities(filter: ?filter) {
> edges {
> node {
> name
> id
> }
> }
> }
> }")
> var response =request.execQuery(params).getAllEntities()
> print(response)
> }


The issue here, is the there must be a generated class for the filter.
Where is the GraphQL schema for Filter ? 

Etienne

**Comment by avalakusuma** [comment]
Thank you so much Etienne. Now I understand we have a separate class for each Filter. 

I found the filter class for my query.

Could you please provide a few examples on how to prepare Filter with multiple conditions. I see builder class in that.

**Comment by etienne-sf** [comment]
Yes I can. 
But please provide your filter GraphQL type definition...

**Comment by avalakusuma** [comment]
I managed to write the filter using the builder class. Thanks again for your help.
