### ISSUE TITLE
CustomScalarTypes do not override graphql types

### ISSUE THREAD

**Issue by markxj** [graphql-java-generator/graphql-maven-plugin-project#43]
In my project, I need the Float type to be mapped as a Double for the extra precision.

I updated my pom to have 

                       <customScalar>
                            <graphQLTypeName>Float</graphQLTypeName>
                            <javaType>java.lang.Double</javaType>
                            <graphQLScalarTypeStaticField>graphql.Scalars.GraphQLFloat</graphQLScalarTypeStaticField>
                        </customScalar>

But the generated code still has Float as the data.

It appears to be because of the call to fillTypesMap in the parseDocuments method overwriting anything that was set up in the postConstruct method.

It's also interesting that graphql-java expects Float to be a java Double based on the implementation of graphql.Scalars.GraphQLFloat, so maybe the call to 
		scalarTypes.add(new ScalarType("Float", "java.lang", "Float", pluginConfiguration));
in postConstruct should really be
		scalarTypes.add(new ScalarType("Float", "java.lang", "Double", pluginConfiguration));

**Comment by etienne-sf** [comment]
Yes, right.
Thanks for pointing this out as precisely.

It'll be available in the next release

Etienne

**Comment by markxj** [comment]
Thanks Etienne

Do you have a time frame for the next release

Thanks

**Comment by etienne-sf** [comment]
I'll try to solve the issue #44, and finish a tutorial. And then release.
It should be done by next sunday.

**Comment by etienne-sf** [comment]
I just released a new version.

Can you check that this issue is actually closed ?

**Comment by markxj** [comment]
It doesn't work for Java 8. The generated QueryExecutor and MutationExecutor use @Deprecated(**forRemoval = true**). forRemoval was added in JDK 9.

**Comment by etienne-sf** [comment]
FUCK !

What's the use to define 1.8 java version for the compiler, if it doesn't check this 1.8 compliance!!

And I can't use 1.8 java on my laptop.
:(

**Comment by markxj** [comment]
I'm also seeing an error in SubscriptionClientWebSocket - the onMessage method has 

Error:(114,31) java: error: unreported exception IOException; must be caught or declared to be thrown

**Comment by etienne-sf** [comment]
I corrected the java 8 issue. 
Had to also add a _release_ tag to the maven compiler plugin.

But I don't see any error or warning on the SubscriptionClientWebSocket.
The line 114 is in a try/catch, that catches all exceptions that can be thrown by the objectMapper.readValue (which is on the line 114).

Do that means that you can't build the plugin ?

**Comment by etienne-sf** [comment]
BTW, I changed the catch, so that it handles IOException.

This should resolve the issue you pointed out.

I deliver a new release now.

**Comment by markxj** [comment]
Thanks Etienner - that fixed it
