### ISSUE TITLE
Schema extension support & Syntax error checking 

### ISSUE THREAD

**Issue by kadoufall** [graphql-java-generator/graphql-maven-plugin-project#45]
Hello,

- Does the plugin provide support for schema extension? In graphql-java, we can use `extend` keyword in SDL to modularise the schema.

The plugin will build the schema below successfully, but the generated code will have compile errors in class `GraphQLDataFetchers`.

```graphql
# top.graphqls 
schema {
    query: Query
}

type Query {
    invoicing: Invoicing
}

# domainA.graphqls
extend type Query {
    billing: Billing
}
```

-  I find that if there are some syntax errors in schema definition, building will still be successful. For example:
```graphql
# A.graphqls 
type Human {
    id: ID!
    name: String
}

# B.graphqls 
# Conflict definition
type Human {
    friends: [Character]
}
```
In the process of generating code, can the plugin performs schema syntax checking and exits when syntax errors are found?

Thanks a lot ~

**Comment by etienne-sf** [comment]
This is up to the graphQL-java, that is used to read the graphQL schema files. 
I didn’t check that, but from the doc, it should work. 

Perhaps the issue is just that the files are read in the wrong order. 

Can you do a first test by putting all the definitions in one file, to be sure of the order of the GraphQL object definitions

Étienne

**Comment by etienne-sf** [comment]
I'll add a way to control the order of files. This implies to change the plugin parameters. 

I have to think a little around that, to make he good move.

**Comment by kadoufall** [comment]
Thanks, Étienne. I have tried to merge all the definitions into one file. I find that the plugin will still generate the code successfully even if the schema has conflicting definitions. For example:
```graphql
type Author {
  id: ID!
  name: String!
}

# conflicting definition
type Author {
  country: String!
}
```
The generated `Author` POJO will only have the last defined attributes and the previous definitions are ignored. In this example the `Author` POJO will only have `country` attribute just like below.
```java
@GraphQLObjectType("Author")
public class Author  {

	public Author(){
		// No action
	}

	@GraphQLScalar(fieldName = "country", graphQLTypeName = "String", javaClass = String.class)
	String country;

}
```

I also tried to add `extend` keyword in later definition, but got the same result.

---
PS:
I need to modularise my schemas in accordance with different domains. So, I want to define the QueryType and MutationType seperately in each domain, but the generation with `extend` keyword seems to have some problems. 

Now I define QueryType and MutationType seperately and merge them by [graphql-schema-utilities](https://github.com/awslabs/graphql-schema-utilities), then generate code with this tool. 

Thanks for your wonderful work ~

**Comment by etienne-sf** [comment]
Hello,

  Thanks for the comment !
:)

I'll update the plugin to allow to use such separate schema files.

And I guess that the point with the two different definitions of the Author are bugs. I'll also work on this one.


The good news is, if I understand correctly your last comment, that you have a workaround. So I can finish a work I started in another branch, before working on these issues.

Etienne

**Comment by kadoufall** [comment]
Yeah. I find a solution for my problem. 

Thanks for your reply and concern ! 😊

**Comment by etienne-sf** [comment]
Ok, I repeated and solved the  'extend' issue.

It will be available in the next release
