### ISSUE TITLE
Strings not properly escaped for JSON

### ISSUE THREAD

**Issue by johanngoltz** [graphql-java-generator/graphql-maven-plugin-project#46]
I'm trying to use the generated client classes to send strings to a GraphQL endpoint. These string sometimes contain special characters that need to be escaped in JSON, such as TAB, CR, LF. But, they are sent as-is, so the JSON sent to the server is malformed.

For example, in this query

```
mutation activateMigration {
  activate(activation: {
    tenants: ["	some-string	"]
  })
}
```

the string contains a TAB character. I would expect the string to be escaped, so that the JSON sent to the server would look like this JSON generated by graphiql:

```
{"query":"mutation activateMigration {\n  activate(activation: {\n    tenants: [\"\tsome-tenant\t\"]...
```

but instead, it still contains the TAB characters:

```
{"query":"mutation activateMigration {\n  activate(activation: {\n    tenants: [\"	some-tenant	\"]...
```

[graphql-java seems to escape all strings according to the JSON rules](https://github.com/graphql-java/graphql-java/blob/4a0a7afdcb03a2ed821a054d6634b5653c772e48/src/main/java/graphql/util/EscapeUtil.java#L18), as does graphiql. But [this library only escapes "](https://github.com/graphql-java-generator/graphql-maven-plugin-project/blob/5455ff59e1ae3731fed22a4710690e77d5bde90e/graphql-java-runtime/src/main/java/com/graphql_java_generator/client/request/InputParameter.java#L536). Is this a bug, or working as intended?

**Comment by etienne-sf** [comment]
Hello,

It’s not an intended feature.

In other words, it’s a bug. 

What is the impact on your side ? 
Can this correction wait for august, around the 20th ?

Étienne

**Comment by johanngoltz** [comment]
Alright, in that case I would like to prepare a PR myself to get rid of that _unintended feature_. Impact on our side is that we have to escape all strings that might contain those characters before passing them to the MutationExecutor.

**Comment by etienne-sf** [comment]
I’ll be glad to accept this PR. 
:)
