### ISSUE TITLE
How to change authentication token in request?

### ISSUE THREAD

**Issue by adlaika** [graphql-java-generator/graphql-maven-plugin-project#48]
I'm trying to create a client that can hit a graphql endpoint that requires an OAuth2 access token in the "Authorization" header of the request. 

It seems like I can only do this by calling `ClientBuilder.register` _at the time I create the `javax.ws.rs.client`_. As the client is pretty heavyweight, I'd prefer to only create it once, and change the token before each new request. 

Is there some way of changing request headers without creating a new `javax.ws.rs.client`?

**Comment by etienne-sf** [comment]
Hum,

The plugin currently doesn't provide additional entry point, so yes, you need to create a new javax.ws.rs.client.Client, and provide it to the QueryExecutor.

Then, to refresh the Client configuration, and change the OAuth token, it's out of the scope of this support.
I guess you'll find all the documentation in the document for the implementation you use. The samples given with the project are done with Jersey.

What are you using ?

What implementation are you using

Etienne

**Comment by adlaika** [comment]
We're using `javax.ws.rs.client.Client`.

We had a working prototype where we rebuild the Client with a new access token on a per-request basis--my question wasn't on how to accomplish that. I wanted to know if I'd missed some interface detail that would allow us to change the access token without instantiating a new Client each time. It doesn't sound like that's the case.

This is unfortunate, as many use cases for a graphQL client involve providing a separate access token at the time of request, and forcing the caller to rebuild the Client each time isn't particularly efficient. 

Perhaps the generated queries could take an HTTP request as a parameter, to which an access token can be added as needed?

For our use case, we ended up dropping generation and moving to handwritten queries, as ours are pretty simple.

**Comment by etienne-sf** [comment]
I did not dig into this use case.

My understanding is that, as you have the Client instance, you can interfere with it, and change the token.

I'm glad that you've found a solution.

I finish my current work (about Real Connection), then I'll check that, as obviously, it's a useful use case.

I'll let you know.

Etienne

**Comment by etienne-sf** [comment]
I'm now working on this one.

Not easy, as the Jersey Client doesn't have a real support for OAuth.
I'm currently enabling the Spring WebClient. This will insure to have a real up-to-date client technology. 
Including various authentication method, including OAuth.

Etienne

**Comment by CodeBreakerK** [comment]
Hi Etienne
Could you work on this one, 

asking since i need this feature for my application.

**Comment by etienne-sf** [comment]
Hello,

Since the 1.12.x releases, the client is a Java Spring application.

It can manage OAuth authentication.

Take a look at these pages:
* On client side: https://graphql-maven-plugin-project.graphql-java-generator.com/client_oauth2.html
* On server side: https://graphql-maven-plugin-project.graphql-java-generator.com/server_oauth2.html


Does it help ?

Etienne

**Comment by CodeBreakerK** [comment]
Hi Etienne

Thanks for the help.
Actually we have to sign request with AWS signature version 4.

and we assumed it would be doable with oAuth, but then we figured, it would make it complicated.

Is there a way to access it using http authorization header?
I could not see anywhere http client exposed where i can add the header.

Best
Karan

**Comment by etienne-sf** [comment]
Hello,,

I don't have the direct answer to your question.

But as you can run the client app as a Spring Boot App, I think that you can find a lot information about this.

Etienne

**Comment by CodeBreakerK** [comment]
Cool, thanks for the help.

**Comment by etienne-sf** [comment]
For instance, you can search for this:

spring httpclient bean
