### ISSUE TITLE
Enum support seems broken

### ISSUE THREAD

**Issue by ekalinichev** [graphql-java-generator/graphql-maven-plugin-project#49]
I have following schema: 

```graphql
enum Title {
  DR,
  MR,
  MS,
  MRS
}

type Account {
  id: Int!
}

input SignupForAccountInput {
  title: Title!
}

type Mutation {
  signupForAccount(input: SignupForAccountInput!): Account!
}
```

When trying to make following request, it fails:

```graphql
mutation {
  signupForAccount(input: {
    title: MR
  }) {
    id
  }
}
```

On this code:

```java
  public Object invokeMethod(Method method, Object o, Object... args) {
    try {
      return method.invoke(o, args);
    } catch (IllegalArgumentException | InvocationTargetException | IllegalAccessException var5) {
      throw new RuntimeException("Error when executing the method '" + method.getName() + "' is missing in " + o.getClass().getName() + " class", var5);
    }
  }
```

The problem is `args[0]` is "MR", as string, and generated method is `void setTitle(Title title)`. It seems that mapping isn't working correctly with enum type. Couldn't find anything in Issues or in SO, so creating a new one.

**Comment by etienne-sf** [comment]
Hello,

 As a first reaction, your request is invalid. You have a comma after MR.
It doesn't seem related to the thrown exception, but you never knows...  :)

Then, for input type, you should use prepared queries with Bind Variables.

For more information, you can search "_bind parameter_" in this page: https://graphql-maven-plugin-project.graphql-java-generator.com/client.html

Etienne

**Comment by ekalinichev** [comment]
@etienne-sf thanks for the response!

- Updated my example, this is not a real request I'm making, it's just rest of schema is irrelevant so I didn't post it
- My report is about server mode, I'm making request from external client to server generated by graphql-maven-plugin, am I posting in wrong repo?

**Comment by etienne-sf** [comment]
Hello,

I confirm the issue. Which is not a surprise for you, I guess.
It's solved, but I want to add proper integration test cases.

I'll deliver a new version, with this issue corrected, in a few days.

Etienne

**Comment by ekalinichev** [comment]
Thanks a lot for looking into this!

**Comment by etienne-sf** [comment]
Ok, I just released a new version.

It has taken some time, as I did some refactoring, to make this part of the code cleaner.

Please, tell me if it's Ok on your side.

Etienne
