### ISSUE TITLE
Support for nested lists

### ISSUE THREAD

**Issue by markxj** [graphql-java-generator/graphql-maven-plugin-project#50]
Our model contains a matrix of Float's represented by a field

type Test {
  matrix: [[Float]]!
}

which is valid graphQL schema.

When using the client generator, we get an error: 

Case not found (subnode of a ListType). The node is of type graphql.language.ListType (for field matrix)

Without this support, we have to try and make matrix and array of another type which then contains the 2nd array which is not as correct.

Is there some other workaround for nested lists?

**Comment by etienne-sf** [comment]
Grrr...  It seems I don't receive the notifications.
Sorry for the response delay

There is no workaround yet. But I'll work on this one.

Etienne

**Comment by etienne-sf** [comment]
Ok, it's a complex one. Lot's of rework, as the fact that the plugin accepts only one level of lists was hard-coded at numerous places.
This is now solved.

I now have issues to deserialize the JSON response, especially with type like [[ObjectType]]

Etienne

**Comment by etienne-sf** [comment]
I released yesterday the 1.11 version.


Can you confirm that your issue is solved, from your point of view ?

Etienne

**Comment by markxj** [comment]
Looks good to me
