### ISSUE TITLE
Log4j dependency

### ISSUE THREAD

**Issue by oliviercoma** [graphql-java-generator/graphql-maven-plugin-project#52]
Hello,

The dependency on log4j was previously removed part of the commit 44c65a93b8aec32b7938dc8e6afb3df855f1e710 but commit e3c230b7f627ae700dae15137e2d38821281b935 re-introduced a dependency on log4j causing conflicts when using other SLF4J backend and force to add an exclusion in the POM / Gradle file.

**Comment by etienne-sf** [comment]
Hum,

Yes, I was thinking about removing all log4j dependency.

Thanks for the report.
I'll correct that for the next release.

Etienne
