### ISSUE TITLE
[Update proposal] Extension field in client Error class as Map<String, Object>

### ISSUE THREAD

**Issue by Lorantus** [graphql-java-generator/graphql-maven-plugin-project#55]
Hi,

I propose you to update the "extensions" field in the "com.graphql_java_generator.client.response.Error" class.

The current (june 2018) [GraphQL Specification](http://spec.graphql.org/June2018/#sec-Errors), chapiter "7.1.2 Errors" is talking about the "extensions" field as "This entry is reserved for implementors to add additional information to errors however they see fit, and there are no additional restrictions on its contents."

According to this and as the content of "extensions" is free to the implementors I propose you to update the class with this code : 
```java
public Map<String, Object> extensions;
```
Using "Object" is a "fourre-tout" accroding to "free to the implementors" is easy. Free to the client to know how to cast Object map.

I faced the trouble with this class as error client of a Appollo Server. I had to update the Error class.

Keep me in touch.

**Comment by etienne-sf** [comment]
Thanks for the proposal

I understand properly, the extensions property of Error should be Map<String, Object> instead of Map<String, String, to properly desierialize anything that is allowed there, as the specification is very open here.
Then it's up to the client application code to manage it.
(in other word, there is no other update needed in the plugin code)

That's correct ?

Etienne

**Comment by Lorantus** [comment]
Yes.Correct.

**Comment by Lorantus** [comment]
Yes.Correct and it's enough at first time.

That a other point in my mind and it is up to my proposal, but....

I think it could be a good idea to think about exceptions that manage Error class like adding the instance of returned Error by the request in exceptions. But it will help the generated code user to access the Error. At this time, it is no possibility to read the instance. GraphQLRequestExecutionException will use a aggregated of Error#message. Other fields are never accessible. In a other way Error is not usable by the generated code user.

I don't think it is a "must-have" and it is just a "nice-to-have". The client will throw exceptions to a console log out most of the time and it is enough.

**Comment by Lorantus** [comment]
Yes. Correct and it's enough at first time.

That a other point in my mind and it is up to my proposal, but....

I think it could be a good idea to think about exceptions that manage Error class. I think about adding the instance of returned Error by the request in exceptions. It will help the generated code user to access the Error. At this time, it is no possibility to read the instance. GraphQLRequestExecutionException will use a aggregated of Error#message. Other fields are never accessible. In a other way Error is not usable by the generated code user.

I don't think it is a "must-have" and it is just a "nice-to-have". The client will throw exceptions to a console log out most of the time and it is enough.

**Comment by Lorantus** [comment]
To up it.
Any next ? MR propose ?

**Comment by etienne-sf** [comment]
Hello,

The main issue, when using it as a `Map<String, Object>` is that when deserializing, the target Java class must be known. 

Who can the plugin guess that ?
Especially when the Java class may change, depending on the map's key.


In the last release, the _extensions_ attribute has been added. It's currently a `JsonNode`, which means that it can contain anything.
It's then up to the client code to decrypt it, according to what is known about the server response. 

It's not very satisfying, but I don't know how to do it better.

Perhaps a `Map<String, JsonNode>` would be a first step, as the GraphQL spec says:
> GraphQL services may provide an additional entry to errors with key extensions. This entry, if set, must have a map as its value. This entry is reserved for implementors to add additional information to errors however they see fit, and there are no additional restrictions on its contents.

**Comment by etienne-sf** [comment]
I've think about this, and here is a proposal which seems a good one. Please tell me what you think about it:

* Let the `extensions` field, as is (this prevents error on any existing implementation)
* Add a `extensionsAsMap` field, that would be the `Map<String, JsonNode>` I talked about
* Add a `getExtensionsField(String key, Class<?> clazz)` that would return the content value of this key, taken into the `extensions` server response, and mapped into the given _clazz_

**Comment by Lorantus** [comment]
It is better to not use the `Object` "fourre-tout" : "Object is you last chance".

I face a runtime error -response is from Appollo Server- with this type (runtime error is a cast) : 
`public Map<String, String> extensions;`

The absolute is to remove or change the type. But if I you want to keep a string value the free server represenation the code implementation that call the extensions field update have to be done. Maybe using the JsonNode object could be a solution with a "toString()" ?

Adding a getter to cast to a _clazz_, with `JsonNode` hidden in `Error` class is a solution that sounds good and will remove the idea of "fourre-tout" map.

**Comment by etienne-sf** [comment]
Hello,

I added the _extensions_ capability, and the method I documented here above. They will be available in the next release.

But I have a question about this:
> I face a runtime error -response is from Appollo Server- with this type (runtime error is a cast) :
> `public Map<String, String> extensions;`

I don't understand this, as _extensions_ is currently a `JsonNode`, note a `Map<String, String>`.

What did I miss ?

**Comment by Lorantus** [comment]
It is about your 1st proposition :
> Let the extensions field, as is (this prevents error on any existing implementation)

You can keep `extensions` as `Map<String, String>` but you have to update function that call the setter. When I receive a error object from the Appollo Server I have a Map to String cast error by this setter. You can simply fill the map value with the string representation of the corresponding `JsonNode`. I also note that keeping `extensions` field is to prevents error on any existing implementation.

I'm talking about `extensions` and not about `extensionsAsMap`.

**Comment by etienne-sf** [comment]
Ok, I found the issue (of this discussion). 

There are two _extensions_ field, at two places in the GraphQL response:

1. One at the root of the GraphQL response, along with the _data_ and _errors_ fields.
2. One in the `Error` structure (content of the _errors_ root field)

From the beginning, you're speaking about the second one.
I switched to the first one in my two last messages.


So:
1. Thanks to my last commit, the response root _extensions_ field can now be retrieved
2. I still have to do the same think, for the `Error.extensions` field

To respect the second one, I'll update the Error class like this :

```
public class Error {
...
	public Map<String, JsonNode> extensions; // instead of the current Map<String, String> extensions

	public Map<String, JsonNode> getExtensionsAsMap() {
...
	}

	public <T> T getExtensionsField(String key, Class<T> t) throws JsonProcessingException {
...
	}
```

I think I'm back on track, there.

Can you confirm that?

Etienne

**Comment by Lorantus** [comment]
I confirm.

Laurent

**Comment by etienne-sf** [comment]
You can now check the 1.13 release.

Everything should be ok now.
