### ISSUE TITLE
Mapstruct support

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#59]
Hello Etienne,

I tried to get mapstruct working to translate between the classes the java-generator created and DTO classes that are used to call the services.
Unfortunately that doesn't work as hoped.
The mapstruct-generated Impl-class only calls the builder() of "your" class.
And when I annotate the function with @Mapping for the id field, I get a compile error, that that class doesn't have that property.

Do you happen to know if mapstruct and the classes of the graphql-java-generator work together?
And if yes, how?

Kind regards,
Markus

**Comment by etienne-sf** [comment]
Hello, 

I don't know mapstruct.

Did you try lombok ?
https://projectlombok.org/

Etienne

**Comment by mheidt** [comment]
Yes, but jhipster is using mapstruct when it generates the sources.

https://www.jhipster.tech/using-dtos/

I and I guess lot more people in the future would prefer to use that one.

**Comment by mheidt** [comment]
Ok,
It's the builder pattern.
You need to add an annotation for every field
@Mapping(target="withId")
I will ask them to automate that.
https://github.com/mapstruct/mapstruct/issues/2331

Thanks for your time, Etienne

**Comment by mheidt** [comment]
It's this, where you find the solution
https://github.com/mapstruct/mapstruct/issues/2330
