### ISSUE TITLE
Feature request: add support for scalar types e.g. Long

### ISSUE THREAD

**Issue by abedeoan** [graphql-java-generator/graphql-maven-plugin-project#6]
The plugin seems to be missing support for scalar types e.g. Long. 

The work-around that my team is currently using was to replace Long with Float in the queries. However it would be nice to have the plugin extended as to support custom scalar types.

**Comment by etienne-sf** [comment]
I plainly agree.
This is the next step

**Comment by etienne-sf** [comment]
Most of the work is done. I need full testing, before making it available

**Comment by abedeoan** [comment]
We are looking forward to test the new feature!

**Comment by etienne-sf** [comment]
Please have a check, I just commited the whole stuff.

I'm now working on the doc, before making a new release

**Comment by etienne-sf** [comment]
Check the allGraphQLCases sample : it uses Date and Long scalars

**Comment by abedeoan** [comment]
Hi Etienne!

Thank you for all your hard work!
We will perform tests the upcoming days and get back to you with feedback next week. 

Regards,
Amelia

**Comment by etienne-sf** [comment]
Grrrr...

Thank you, now corrected.
I also documented the stuff: I'll do a release, if possible today. Then I'll publish the updated site.

**Comment by etienne-sf** [comment]
Hello,

 You can check the doc here:
https://graphql-maven-plugin-project.graphql-java-generator.com/customscalars.html

**Comment by abedeoan** [comment]
Hi Etienne,

I can confirm that the support for custom scalar Long works as expected. 
We didn't try yet the support for Date / adding our own scalars - so there is no feedback we can provide on this topic yet.

We can consider this Issue closed. 

Regards,
Amelia
