### ISSUE TITLE
Authorization gets lost

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#60]
We are using Feign to generate our REST clients.

The first call that is triggered in the DataFetchersDelegateQuery implementation works as expected.
A call to SecurityContextHolder.getContext().getAuthentication() returns the bearer string.

But a second call that is triggered in a Non-Root DataFetchersDelegate  fails, because the Authorization is empty.
SecurityContextHolder.getContext().getAuthentication() is empty this time.

In the log you can see, that this is the case, once the DataFetcherDelegates is in the onPool worker threads.

Is there a solution to get the UserJWT? 
I didn't see it in the DataFetschingEnvironment either and getVariables() is unmutable, so that I cannot pass it.

Thanks a lot,
Markus

**Comment by etienne-sf** [comment]
I fear that this issue is all out of the plugin, as JWT is currently not managed by the plugin.

Etienne

**Comment by mheidt** [comment]
But couldn't the DataFetchingEnvironment provide a Map where the user can store values like the securityContext.
Why is getAttribute() immutable?

**Comment by mheidt** [comment]
Etienne,

I really think, you made a great job with this generator. 
I want to use the generated classes without changing them.

I really need help here, because the only solution I found for this issue is to use good old singletons. 
And this can't be the solution in the year 2021

I didn't find any part of DataFetchingEnvironment where I could store something.

I tried a @Component UserJwtStore that holds a Map from ExecutionId to Jwt.
But the autowiring doesn't work in the other DataFetchersDelegate implementations. A new UserJwtStore is created.

This solution would be sub-optimal anyways because I have to prune that map after a while in order to keep it small.

Does anybody have an idea? I prefer a stateless option.

Cheers,
Markus

**Comment by mheidt** [comment]
@etienne-sf , I made some progress.
I found a GraphQLInvocation implementing legacy class in my project which breaks the dependency injection.

But the org.springframework.security.core.contextSecurityContextHolder.getContext().getAuthentication() is still empty.

That's why I wrote a store

```
@Component
public class UserJwtStore {
    private Map<ExecutionId, String> keyStore = new HashMap();

    public void put(ExecutionId executionId, String userJwt){
        this.keyStore.put(executionId, userJwt);
    }

    public String get(ExecutionId executionId){
        if (keyStore.containsKey(executionId)) {
            return this.keyStore.get(executionId);
        }
        return null;
    }

    /**
     * This is a security breach
     * @return
     */
    @Deprecated
    public String get(){
        log.warn("UserJwtStore.get((any from {} possibilities)). This function should never be called",this.keyStore.size());
        if (keyStore.size()>0) {
            return this.keyStore.values().iterator().next();
        }
        return null;
    }
}
```

Unfortunately I have to use the last function, which is just giving the first value.
I have to rewrite it to get the latest, but for testing it's ok.

This is where I have the issue:
```
 @Override
  public List<ShortnameResponseMM> batchLoader(List<Long> keys) {
        String userJwt = userJwtStore.get();
        Authentication userJwt2 =   SecurityContextHolder.getContext().getAuthentication();
        log.debug("ShortnameResponseDF.bacthloader userJwt: {}, SecurityContextHolder: {}", userJwt, userJwt2!=null?userJwt2.getCredentials():"null");
```
If the batchLoader would pass the executionId, I would be able to map the correct value. But nevertheless, this approach is bad, because the store grows and I need to add a time based pruning as well.

If you won't provide a datastore that is passed to the batchloaders as well, I only see the alternative option to define fields in graphql.
But that's bad style. Defining fields that are needed for the internal use only!?
Anyways I didn't test if I can change their values, so I don't know if that hack is a valid strategy.

**Comment by etienne-sf** [comment]
Hello,

  I'm working in this subject. I just finished to work for OAuth authorization. It's on another branch (), and I'll merge it soon in the master branch.
You can check the allGraphQLCases samples, which is based on Opaque OAuth tokens.

But your issue seems more to retrieve the JWT token in DataFetchersDelegate.

Autowire should work, as all DataFetchersDelegate are Spring beans, and loaded by Spring

Then, please note that the generated application is a standard graphql-java application, as stated in this blog: https://www.graphql-java.com/blog/graphql-java-aims-to-be-used-directly/ (with the use of the GraphQL Java Spring project). So you may finf hint there.

Etienne

**Comment by mheidt** [comment]
OK, the MODE_INHERITABLETHREADLOCAL made it work:

```
@Bean
public MethodInvokingFactoryBean methodInvokingFactoryBean() {
    MethodInvokingFactoryBean methodInvokingFactoryBean = new MethodInvokingFactoryBean();
    methodInvokingFactoryBean.setTargetClass(SecurityContextHolder.class);
    methodInvokingFactoryBean.setTargetMethod("setStrategyName");
    methodInvokingFactoryBean.setArguments(new String[]{SecurityContextHolder.MODE_INHERITABLETHREADLOCAL});
    return methodInvokingFactoryBean;
}
```
