### ISSUE TITLE
Question about UUIDs vs Long (javaTypeForIDType)

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#61]
Hello Etienne,

Our database schema is using Long IDs. 
That's why I was setting javaTypeForIDType to true.
But I was wondering, if using random UUIDs is the better option.
Or does this make no sense, if the database/repository doesn't work with UUIDs?

Merci,
Markus

**Comment by etienne-sf** [comment]
A UUID can be mapped into a Long.
So I guess you can have java code that uses UUID, and map it to a Long into that database.

But I don't know your project and its constraints.

Are you sure that all the Long IDs on your database can be mapped into a UUID, now and in the future ?

Etienne

**Comment by mheidt** [comment]
The idea was to create an UUID from the String
"<service>:<entity>:<id>"

But as there is no way to reverse the direction and get the String back from the hash value of the UUID, I guess I have 
either to store the UUID->rawUUIDString mapping in the service, the graphql is running in,
or to go back to javaTypeForIDType and see, if I really need UUID.
We thought UUID might be convenient in the Apollo client  when it comes to cashing.

Is my assessment correct?

**Comment by etienne-sf** [comment]
I can't answer to you on this point.

You're going way out of the scope of this plugin.
