### ISSUE TITLE
RelayConnection vs List error

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#62]
Hello Etienne,

I wanted to test RelayConnection today and facing the following problem

```
type Query {
  locations(filter: FilterMM): [LocationMM!] @RelayConnection
```

and in the implementation I am using for testing so far
```
@Override
public LocationMMConnection locations(DataFetchingEnvironment dataFetchingEnvironment, FilterMM filter) {
    LocationMMConnection result = new LocationMMConnection();
    List<LocationMMEdge> edges = new ArrayList();
    LocationMMEdge edge = new LocationMMEdge();
    edge.setCursor("100149");
    LocationMM locationMM = new LocationMM();
    locationMM.setId(100149L);
    edge.setNode(locationMM);
    edges.add(edge);
    result.setEdges(edges);
    return result;
}
```
First of all, I am wondering how I get the batchloading hooked up here.

But more urgently: When I call 

```
{
  locations(filter: { businesscaseIds: [1]}
  ){
    id
  }
}
```

I get the following error
`n.graphql.execution.ExecutionStrategy    : Can't resolve value (/locations) : type mismatch error, expected type LIST got class de.lsy.cmon.aggregator.graphql.LocationMMConnection`

**Comment by mheidt** [comment]
And when I want to be smart and change the schema to reaturn LocationMMConnection, i get the error

`Failed to execute goal com.graphql-java-generator:graphql-maven-plugin:1.11.2:generateGraphQLSchema (default) on project aggregator: The Query.locations field has the @RelayConnection directive applied, but is not a list. `

**Comment by etienne-sf** [comment]
I'll add a test case on this one.

I'll give you feedback once it's done.

Etienne

**Comment by etienne-sf** [comment]
Hello,

This use case is unclear from me. 
My tests properly include the @RelayConnection on a field of type list. 


What kind of server and client are you using ?

Are they both developped with the GraphQL plug-in?

**Comment by mheidt** [comment]
I have just tested with the latest build and the error is fixed.
The only thing I saw now is, that the generated_schema.graphql defines the scalars
Milliseconds, Seconds and Decimal which weren't used in my project, so that the startup of the application failed.
But when I remove those lines I can confirm, that the list error is gone.
