### ISSUE TITLE
generateGraphQLSchema not creating file

### ISSUE THREAD

**Issue by GuzziMP** [graphql-java-generator/graphql-maven-plugin-project#63]
Hi Etienne,
in Changelog for 1.11 https://github.com/graphql-java-generator/graphql-maven-plugin-project/blob/master/CHANGELOG.md
you mention, that we can output the "resulting" graphql schema, when applying the "addRelayConnections".
I tried that by adding or replacing the goal with 'generateGraphQLSchema' but didn't find the output file - is there anything else required?

**Comment by etienne-sf** [comment]
Hello,

Please take care that I sometimes did I typo in the doc: the directive name is _@RelayConnection_ (and not _@RelayConnexion_)

You'll have to use the generateGraphQLSchema (as you've seen). The doc for this goal is here: https://graphql-maven-plugin-project.graphql-java-generator.com/graphql-maven-plugin/generateGraphQLSchema-mojo.html

Take a look to the _targetSchemaFileName_ plugin parameter, to select where the file should be generated.

You'll find a sample in this pom: https://github.com/graphql-java-generator/graphql-maven-plugin-project/blob/master/graphql-maven-plugin-samples/graphql-maven-plugin-samples-allGraphQLCases-client/pom.xml


Does it help ?

**Comment by GuzziMP** [comment]
Hi Etienne,
thanks, that helped me :-) - I didn't look in the client example - adding the config from there to the server pom also gives me the "merged-schema" - so I'll close the issue,
Thanks, Guzzi
