### ISSUE TITLE
ExecutionStepInfo Arguments not as Map

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#67]
Hello Etienne,

Is there a reason, why the arguments in ExecutionStepInfo are LinkedHashMaps and not of the type the plugin generated?
There is no switch, so that I can have them in that way?

Thanks,
Markus

**Comment by etienne-sf** [comment]
I don't understand your question. 
I'm reading it on my phone, and I can't check it for now. 

But it seems to me that you're reading the graphql-Java code, not the code generated by the plug-in. 

Is this correct ?

**Comment by mheidt** [comment]
Yes, it's not a bug but rather a feature request.
BUT. mapstruct isn't ready yet. But they are working on a feature so that you could generate 
mappers easily for those entities that are parameters and could be used as arguments in the DataFetchingEnvironment or BatchLoaderEnvironment.
You can consider this on hold and I inform you, if mapstruct is capable of an easy mapping.
Now you have to implement each mapping manually...
But of course, you can consider this feature out of your scope.

**Comment by etienne-sf** [comment]
Hum,

The plugin is complex enough. And I want it to remain as simple as possible for the plugin's user.

Considering this, I'm not sure that adding mapstruct to the plugin technologies will help. I think it will make it more complex, so less usable.

As you're apparently thinking about it, can you can close this issue ?
You'll reopen it, or open a new one, once you're done on this point?
