### ISSUE TITLE
Batchloader and Caching

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#68]
Hi Etienne,

Could it be, that the results of the batchloading are cached?
The second call doesn't stop by in the batchloader function of my delegate.
Is there an annotation I can switch it off with?
Sometimes caching makes sense but in other cases my calls get "Live"-data.

Thanks,
Markus

**Comment by etienne-sf** [comment]
Yes, I've seen that. 

And I'm not that sure. 

I don't manage the data loader. The generated code uses an existing library. 
For more information, you should take a look at the GraphQL-Java, as the generated code is just what you would have developed, to use it. 
I'll also dig into it, to give some hints on how to do this, or what doc should be read. 

Étienne

**Comment by mheidt** [comment]
First of all I hacked around it by using random ids and managing an internal hashmap from real id to that random id.

But if we want to have it nice, we need to let GraphQLInvocation handle it.
https://blog.softwaremill.com/graphql-dataloader-in-spring-boot-singleton-or-request-scoped-16699436f680

If there would be two DataLoaderRegistries. One for the application scoped dataloaders and one "registry" that holds the information, so that the GraphQLInvocation can create new DataLoaders with each request and adds the application-scoped from the original DataLoaderRegistry.

**Comment by mheidt** [comment]
@etienne-sf 
I saw, that you changed something in 1.12.1.
Now all dataloader are request-scoped.
But i was using my own @Primary GraphQLInvocation in order to log the calls with sleuth.
Do you know, how I can override/hook into it?

**Comment by mheidt** [comment]
But I see the problem. There are already 2 and there can only be one Primary. So when I come in as 3rd.
So the only option would be, if you provide a switch so that you don't generate the GraphQLInvocation at all.
Right?
Maybe only a commented version of it...

**Comment by etienne-sf** [comment]
There are other ways. I'll exclude the default one. So mine won't need to be Primary. 

And I'll suggest the graphql-java-spring another way to do this that would not need any such component on the plug-in side. 

In the meanwhile, can you test without as is, for instance by removing this component from the generated code ?
(Dont't forget to copy/paste the code that creates a new DataLoaderRegistry for each request invocation)

**Comment by etienne-sf** [comment]
I just commit an update, in which I exclude the DefaultGraphQLInvocation. So the customGraphQLInvocation created by the plugin is no more marked as _@Primary_.
I'll submit a PR to the graphql-java-spring project, that allows to have a DataLoaderRegistry par request as it's done here, in the generated code.

I didn't create a new release yet.

Can you checkout the plugin, and test from a local build ?
If you do that, the plugin version is _local-SNAPSHOT_, instead of 1.12.1

**Comment by mheidt** [comment]
Thanks Etienne,

It works. It stopped at the breakpoint in my GraphQLInvocation 👍 

Merci,
Markus

**Comment by etienne-sf** [comment]
Markus,

  I'm about to release a new (minor) version.

Can you confirm to me that all your opened issues are solved, and just waiting for a new release ?

**Comment by mheidt** [comment]
Hi Etienne,

Actually I am really working productive right now :)
So yes, you can build a new minor.
There is one "smal"l thing we like to see and that I might look into myself when I have time left.
You remember the Batchloader ID/value discussion?
It would be nice, if we could force the Batchloading with an annotation. Or define the return value of the returning object within that ResponseObject.

Thanks,
Markus
