### ISSUE TITLE
Maven plugin: Do not generate sources if schema was not changed

### ISSUE THREAD

**Issue by oliviercoma** [graphql-java-generator/graphql-maven-plugin-project#69]
Hello,

Currently, the maven plugin generates Java source code even if the schema was not changed. This is further causing issues as all the subsequent plugins will be executed instead of skipped (e.g. maven-compiler-plugin will re-compile the whole module).

This is especially problematic in CI/CD builds where each stage would execute different phases as each stage would actually recompile everything.

In most cases, this is only loosing a bit of time, but in some cases, it can make the pipeline to fail (e.g. a binary that must be present for a phase, but not for others must now be available for all phases).

Work around:
Using profiles to skip the plugin entirely when not needed. Interestingly, source directory must be added manually with build-helper-maven-plugin or the compiler plugin will detect classpath change and try to recompile.

```
<profiles>
	<profile>
		<id>skipSourceGeneration</id>
		<build>
			<plugins>
				<plugin>
					<groupId>com.graphql-java-generator</groupId>
					<artifactId>graphql-maven-plugin</artifactId>
					<version>${graphql-maven-plugin.version}</version>
					<executions>
						<execution>
							<id>graphql</id>
							<phase>none</phase>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>build-helper-maven-plugin</artifactId>
					<executions>
						<execution>
							<id>add-source</id>
							<phase>generate-sources</phase>
							<goals>
								<goal>add-source</goal>
							</goals>
							<configuration>
								<sources>
									<source>target/generated-sources/graphql-maven-plugin</source>
								</sources>
							</configuration>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</build>
	</profile>
</profiles>
```

**Comment by etienne-sf** [comment]
Hello,

This is a good point. I'm working on this one.

I thought it would be simple. But it implies some internal refactoring. There will be a new plugin parameter for that.

**Comment by etienne-sf** [comment]
Ok, I added a new plugin parameter (_skipGenerationIfSchemaHasNotChanged_) for that. It prevents the code generation, if it's unnecessary.

But it seems that the add of the source folder, by the build-helper-maven-plugin, forces maven to compile, even if there was no change in the code itself. I guess it's the reason why you've put it also in the profile.

So, once a new release of the plugin is available, with this new parameter, you'll still need to put _build-helper-maven-plugin_ into a dedicated profile.

Etienne

**Comment by etienne-sf** [comment]
Can you give a check on the 1.12.2, that has just been released ?

It contains this _skipGenerationIfSchemaHasNotChanged_ plugin parameter, that should do the trick.

Etienne

**Comment by oliviercoma** [comment]
Helo @etienne-sf,

I've tested this morning and it works as expected, thanks!

I don't have the issue you mentioned with the source directory to be added manually (I'm using Maven 3.6.3). I can completely remove the dedicated profile for build-helper-maven-plugin and it works as intended. As long as the plugin adds itself the source directory regardless of the value of skipGenerationIfSchemaHasNotChanged, I think we are fine.

It really reduces our builds complexity, thank you very much for this.

**Comment by etienne-sf** [comment]
Nice
:)

And you're right, it's a useful stuff. I added a FAQ, with this information. It will be available in next version's site.

So I close this issue.
