### ISSUE TITLE
Error when using InputTypes in the response definition

### ISSUE THREAD

**Issue by etienne-sf** [graphql-java-generator/graphql-maven-plugin-project#7]
Doing a Direct Query with the above Response definition leads to a runtime error:

private static final String PJ_QUERY_RESPONSE_DEF = [Request removed for privacy]

**Comment by etienne-sf** [comment]
The issue is not in the plugin.

The issue is in the PJ_QUERY_RESPONSE_DEF content: this String is itself embedded into a JSON string.

So all its double quote should be prefixed by an anti-slash.

The following lines should do the trick:
private static final String PJ_QUERY_RESPONSE_DEF = "{" +
" id" +
" startTime " +
" equipment {" +
" id" +
" customerName" +
" }" +
" waferProcessJobs { " +
" waferData " +
"(filter: {" +
" performanceDomain: \\\"Overlay\\\"" +
" })" +
"{" +
" dataServiceId" +
" subWaferData {" +
" performanceIndicator" +
" id" +
" }" +
" }" +
" }" +
" }";

**Comment by etienne-sf** [comment]
Please not that you should avoid DirectQueries for complex queries.

Consider preparing queries, with parameter as bind variables.

Etienne

**Comment by abedeoan** [comment]
Hi Etienne, 

Thank you for picking up this item that I reported by e-mail. 

I am adding below a dummy query response - for the thread's completeness. 

private static final String PJ_QUERY_RESPONSE_DEF = "{" +
" id" +
" time " +
" machine {" +
" id" +
" name" +
" }" +
" jobs { " +
" data " +
"(**filter**: {" +
" **domain**: "Mining"" +
" })" +
"{" +
" serviceId" +
" subData {" +
" indicator" +
" id" +
" }" +
" }" +
" }" +
" }";

How should the bind parameters map look like in this situation? 
I tried binding either *domain* or *filter*, but the same error occurs; so maybe I am misusing the API?

**Comment by etienne-sf** [comment]
I reformated your String for better readabilty:
"{id time machine {id name} jobs {data(filter: {domain: "Mining"}){serviceId subData {indicator id}}}}"

The issue here is that the plugin can't currently read the {domain: "Mining"} json part.

So you have to replace the query response by this one:
"{id time machine {id name} jobs {data(filter: ?filterParam){serviceId subData {indicator id}}}}"

This means that there is a Bind Variable of name "filterParam" that must be provided at runtime.
You don't have to provide the map at runtime : the client method allows you to add parameters at the end. The method will create the Map on its own.
These parameters must be couples of values :
* The parameter name (here: "filterParam")
* The parameter value (Here: an object with a "domain" field, whose value is "Mining")

You can see samples in the Forum client project, in the com.graphql_java_generator.samples.forum.client.graphql.PreparedQueries

**Comment by abedeoan** [comment]
Hi Etienne, 

Thank you for the provided example! It answered my questions!

I consider this Issue done. 

Regards, 
Amelia

**Comment by etienne-sf** [comment]
This issue is solved in version 1.2
