### ISSUE TITLE
How can I specify the target folder for standard packages like: client, annotation, exception, etc.?

### ISSUE THREAD

**Issue by boroda4436** [graphql-java-generator/graphql-maven-plugin-project#71]
The problem: I don't want to use a custom folder name `com.graphql_java_generator.exception`. Instead, I want to use smth like: `my.custom.exception`. Same for all other packages and classes inside the `com.graphql_java_generator` package.

Using the `<packageName>my.custom.samples.forum.client.graphql.forum.client</packageName>` property I can specify the package only for entities generated from graphql file.

![image](https://user-images.githubusercontent.com/13794896/107877844-7d0d9c00-6ed7-11eb-9c02-f82e7eb2f6f4.png)

**Comment by etienne-sf** [comment]
Hello,

This code is versionned in git, and has a lot of unit tests attached to it.

So  I see no value, but troubles, to make this dynamic.

What would be the value of changing this _com.graphql_java_generator_ package?

Etienne
