### ISSUE TITLE
1.11.2 Upgrade Path

### ISSUE THREAD

**Issue by kalinwilson** [graphql-java-generator/graphql-maven-plugin-project#74]
I'm confused about the steps to upgrade from 1.11.2 to 1.12.3+. I followed the current instructions and samples to update my generator dependencies to graphql-java-runtime (tried graphql-java-client-dependencies), update the plugin configuration, etc. and I continually get compilation errors because the io.reactor classes (Sinks, etc.) can't be found. 
I tried adding the spring webflux starter dependencies, as well as the reactor dependencies directly with no success.

The samples and examples seem to imply that I build my app around the generated client code as a single app. I generate clients for multiple services as separate artifacts, and bring those into another boot app that employs the clients.

Thanks for any help or advice.

**Comment by etienne-sf** [comment]
Hello,

Can you provide more information on your use case?
* An extract of your POM (or build.gradle) would help to understand the issue
* Are you building a client, or a server part ?

Etienne

**Comment by kalinwilson** [comment]
Here is the parent, and project POM for one of my graphql client projects. I am generating clients only. When I upgrade past 11.2.1 and compile, there are the errors I get. I have not tried to track down additional dependencies. I am building with Spring Boot 2.3.9.RELEASE and don't have the ability to upgrade beyond that at this time.

Parent POM:
<properties>
        <com.graphql-java.version>16.2</com.graphql-java.version>
        <com.graphql-java-extended-scalars.version>16.0.0</com.graphql-java-extended-scalars.version>
        <springboot.version>2.3.9.RELEASE</springboot.version>

        <graphql.generator.version>1.14</graphql.generator.version>
    </properties>
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${springboot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.graphql-java</groupId>
                <artifactId>graphql-java</artifactId>
                <version>${com.graphql-java.version}</version>
            </dependency>
            <dependency>
                <groupId>com.graphql-java</groupId>
                <artifactId>graphql-java-extended-scalars</artifactId>
                <version>${com.graphql-java-extended-scalars.version}</version>
            </dependency>
            <dependency>
                <groupId>com.graphql-java-generator</groupId>
                <artifactId>graphql-java-client-dependencies</artifactId>
                <type>pom</type>
                <version>${graphql.generator.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

Project POM:
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>atlas.ui-aggregation</groupId>
        <artifactId>ui-aggregation-generated-graphql-clients</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>ui-aggregation-user-crud-graphql</artifactId>

    <packaging>jar</packaging>

    <name>ATLAS: ui-aggregation-user-crud GraphQL Implementation</name>
    <description>Uses graphql-generator. Need to make those immune to coverage scanning</description>

    <properties>
        <code-coverage.skip>true</code-coverage.skip>
        <integration.tests.skip>true</integration.tests.skip>
    </properties>

    <dependencies>
         <dependency>
            <groupId>com.graphql-java-generator</groupId>
            <artifactId>graphql-java-client-dependencies</artifactId>
             <version>${graphql.generator.version}</version>
             <type>pom</type>
        </dependency>

        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java-extended-scalars</artifactId>
        </dependency>

        <dependency>
            <groupId>atlas.user-crud</groupId>
            <artifactId>user-crud-graphql</artifactId>
            <version>${atlas.crud.version}</version>
            <classifier>schema</classifier>
            <type>zip</type>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>graphql/</exclude>
                </excludes>
            </resource>
        </resources>
       <plugins>
           <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>unpack</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>atlas.user-crud</groupId>
                                    <artifactId>user-crud-graphql</artifactId>
                                    <version>${atlas.crud.version}</version>
                                    <classifier>schema</classifier>
                                    <type>zip</type>
                                    <outputDirectory>${project.basedir}/src/main/resources</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                            <overWriteSnapshots>true</overWriteSnapshots>
                        </configuration>
                    </execution>
                </executions>
           </plugin>

           <plugin>
                <groupId>com.graphql-java-generator</groupId>
                <artifactId>graphql-maven-plugin</artifactId>
               <version>${graphql.generator.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generateClientCode</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <schemaFilePattern>/graphql/*.graphqls</schemaFilePattern>
                    <packageName>atlas.user.crud.graphql</packageName>
                    <customScalars>
                        <customScalar>
                            <graphQLTypeName>NonNegativeInt</graphQLTypeName>
                            <javaType>java.lang.Integer</javaType>
                            <graphQLScalarTypeStaticField>graphql.scalars.ExtendedScalars.NonNegativeInt</graphQLScalarTypeStaticField>
                        </customScalar>
                        <customScalar>
                            <graphQLTypeName>PositiveInt</graphQLTypeName>
                            <javaType>java.lang.Integer</javaType>
                            <graphQLScalarTypeStaticField>graphql.scalars.ExtendedScalars.PositiveInt</graphQLScalarTypeStaticField>
                        </customScalar>
                        <customScalar>
                            <graphQLTypeName>DateTime</graphQLTypeName>
                            <javaType>java.time.OffsetDateTime</javaType>
                            <graphQLScalarTypeStaticField>graphql.scalars.ExtendedScalars.DateTime</graphQLScalarTypeStaticField>
                        </customScalar>
                        <customScalar>
                            <graphQLTypeName>Long</graphQLTypeName>
                            <javaType>java.lang.Long</javaType>
                            <graphQLScalarTypeStaticField>graphql.scalars.ExtendedScalars.GraphQLLong</graphQLScalarTypeStaticField>
                        </customScalar>
                    </customScalars>
                </configuration>
           </plugin>

           <plugin>
               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-clean-plugin</artifactId>
               <version>${maven-clean-plugin.version}</version>
               <executions>
                   <execution>
                       <id>cleanup-schema</id>
                       <phase>clean</phase>
                       <goals>
                           <goal>clean</goal>
                       </goals>
                       <configuration>
                           <filesets>
                               <fileset>
                                   <directory>${project.basedir}/src/main/resources/graphql</directory>
                               </fileset>
                           </filesets>
                       </configuration>
                   </execution>
               </executions>
           </plugin>
        </plugins>
    </build>
</project>

Compile Errors:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.609 s
[INFO] Finished at: 2021-04-15T08:41:28-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project ui-aggregation-user-crud-graphql: Compilation failure: Compilation failure:
[ERROR] D:\work\atlas-c1d\atlas-service-ui-aggregation\ui-aggregation-implementation-parent\ui-aggregation-generated-graphql-clients\ui-aggregation-user-crud-graphql\target\generated-sources\graphql-maven-plugin\com\graphql_java_generator\client\GraphQLReactiveWebSocketHandler.java:[20,29] error: cannot find symbol
[ERROR]   symbol:   class Sinks
[ERROR]   location: package reactor.core.publisher
[ERROR] D:\work\atlas-c1d\atlas-service-ui-aggregation\ui-aggregation-implementation-parent\ui-aggregation-generated-graphql-clients\ui-aggregation-user-crud-graphql\target\generated-sources\graphql-maven-plugin\com\graphql_java_generator\client\GraphQLReactiveWebSocketHandler.java:[21,35] error: package reactor.core.publisher.Sinks does not exist
[ERROR] D:\work\atlas-c1d\atlas-service-ui-aggregation\ui-aggregation-implementation-parent\ui-aggregation-generated-graphql-clients\ui-aggregation-user-crud-graphql\target\generated-sources\graphql-maven-plugin\com\graphql_java_generator\client\GraphQLReactiveWebSocketHandler.java:[22,35] error: package reactor.core.publisher.Sinks does not exist
[ERROR] D:\work\atlas-c1d\atlas-service-ui-aggregation\ui-aggregation-implementation-parent\ui-aggregation-generated-graphql-clients\ui-aggregation-user-crud-graphql\target\generated-sources\graphql-maven-plugin\com\graphql_java_generator\client\GraphQLReactiveWebSocketHandler.java:[54,1] error: cannot find symbol
[ERROR]   symbol:   class One
[ERROR]   location: class GraphQLReactiveWebSocketHandler<R,T>
[ERROR]   where R,T are type-variables:
[ERROR]     R extends Object declared in class GraphQLReactiveWebSocketHandler
[ERROR]     T extends Object declared in class GraphQLReactiveWebSocketHandler
[ERROR] D:\work\atlas-c1d\atlas-service-ui-aggregation\ui-aggregation-implementation-parent\ui-aggregation-generated-graphql-clients\ui-aggregation-user-crud-graphql\target\generated-sources\graphql-maven-plugin\com\graphql_java_generator\client\GraphQLReactiveWebSocketHandler.java:[54,30] error: cannot find symbol
[ERROR]   symbol:   variable Sinks
[ERROR]   location: class GraphQLReactiveWebSocketHandler<R,T>
[ERROR]   where R,T are type-variables:
[ERROR]     R extends Object declared in class GraphQLReactiveWebSocketHandler
[ERROR]     T extends Object declared in class GraphQLReactiveWebSocketHandler
[ERROR] D:\work\atlas-c1d\atlas-service-ui-aggregation\ui-aggregation-implementation-parent\ui-aggregation-generated-graphql-clients\ui-aggregation-user-crud-graphql\target\generated-sources\graphql-maven-plugin\com\graphql_java_generator\client\GraphQLReactiveWebSocketHandler.java:[152,2] error: cannot find symbol
[ERROR]   symbol:   class EmitResult
[ERROR]   location: class GraphQLReactiveWebSocketHandler<R,T>
[ERROR]   where R,T are type-variables:
[ERROR]     R extends Object declared in class GraphQLReactiveWebSocketHandler
[ERROR]     T extends Object declared in class GraphQLReactiveWebSocketHandler
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by etienne-sf** [comment]
The issue is linked to the `Sinks` class. This class is linked to the Spring reactive, and is a relatively new one.

So this is the reason for this error.

BTW, using Reactive seemed to be a good idea. But it slows down the execution of the first request of some secunds, on my (slow) computer.
I'm in the process of removing all the reactive part. This should solve this issue.

**Comment by etienne-sf** [comment]
Can you check the 1.14.1 release ?

It solves this issue
