### ISSUE TITLE
Custom templates on OBJECT fails

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#75]
Hi Etienne,

I want the objects to be Serializable. 
That's why I thought changing the OBJECT template would be a good idea.

I changed this in the pom
`<templates>
    <OBJECT>graphql/object_type.java.vm</OBJECT>
</templates>`

![image](https://user-images.githubusercontent.com/4159298/111209417-44dba500-85cc-11eb-85a1-767d4b76e791.png)

But when compiling, I get an error
Failed to execute goal com.graphql-java-generator:graphql-maven-plugin:1.12.4:generateServerCode (graphql-generateCode) on project aggregator: Error when Generating object 'ConnectionMM' into

**Comment by etienne-sf** [comment]
The configuration seems ok.
But the error message is truncated.

Can you provide the full one ?

NB : having the generated object classes be serializable seems to be a good idea. It can not be the standard behavior, as defining a Custom Scalar with a non serializable class would break it.

**Comment by mheidt** [comment]
The error message was not very informative

Failed to execute goal com.graphql-java-generator:graphql-maven-plugin:1.12.4:generateServerCode (graphql-generateCode) on project aggregator: Error when Generating object 'ConnectionMM' into D:\LINUX_DEV\git\vimos\backend\aggregator\target\generated-sources\graphql-maven-plugin\de\lsy\cmon\aggregator\graphql\ConnectionMM.java

Hm, but it says also
[ERROR] ResourceManager : unable to find resource 'graphql/object_type.java.vm' in any resource loader.

What am I missing? It's under resources as you can see in the screenshot

**Comment by etienne-sf** [comment]
Yes, I understand it, now. 

This was submitted by a PR. I hadn't see that when if was submitted. 

Currently, the template must be found on the class path. This means that it must be packaged in a jar that is available in the project compile pathclass. 

You can check this in the samples, in the project:
* CustomTemplates-resttemplate is a jar that embed the custom templates. 
* in the CustomTemplates-client Pom file, the CustomTemplates-resttemplate artifact has been added as a dependency for the graphql-maven-plugin 

This is complex, and undocumented. 
I'll change that.

**Comment by etienne-sf** [comment]
Oh no, it's properly documented in the customtemplate page. 

And it's actually mandatory, when this template is loaded by the Velocity _import_ keyword

**Comment by mheidt** [comment]
Ah yes, I had to do the same for mapstruct. Always forget about this.
It works now, thanks.
