### ISSUE TITLE
Use custom template to generate server code

### ISSUE THREAD

**Issue by ruks** [graphql-java-generator/graphql-maven-plugin-project#76]
I'm using graphql-maven-plugin to generate graphQL server code and I'm planning to do some changes to GraphQLDataFetchers. But to provide a custom template for DATA_FETCHER, the templated file should be in the classpath and so I have to implement another jar to add them. 
Is there a better way to apply a custom template than implementing another jar?

**Comment by etienne-sf** [comment]
There is currently no better way.

But I committed last week an enhancement about this. In the next release, you'll be able to put the custom template in the project that uses it (instead of another project or module, that produces a jar that your project will use).

I'm working on a last issue, before doing this release. So I think this next release will come next week-end.

Etienne

**Comment by etienne-sf** [comment]
So, if you're in a hury, you can checkout and build the current code. The release version would then be _local-SNAPSHOT_.
Otherwise, just wait some days, and it will be ok.

**Comment by ruks** [comment]
@etienne-sf thanks for the update. I can test this locally and wait for the release. 

This is really a great news 👍

**Comment by mheidt** [comment]
@ruks
what are those changes.
You know, that you can have custom wiring and datafetchers now?

`@Component
@Primary
public class CustomGraphQLDataFetchers extends GraphQLDataFetchers {
  @Autowired
    protected AreaBDF batchloaderDataFetcherArea;

  public DataFetcher<CompletableFuture<String>> dataFetchersDelegateLocationMMAreaWithDataLoader() {
        return dataFetchingEnvironment -> batchloaderDataFetcherArea.get(dataFetchingEnvironment);
    }
`

and
`@Component
@Primary
public class CustomGraphQLWiring extends GraphQLWiring {
    @Autowired
    CustomGraphQLDataFetchers graphQLDataFetchers;

 @Override
    protected TypeRuntimeWiring.Builder addWiringForLocationMM(TypeRuntimeWiring.Builder typeWiring) {
        typeWiring = super.addWiringForLocationMM(typeWiring);

  
      typeWiring.dataFetcher("area", graphQLDataFetchers.dataFetchersDelegateLocationMMAreaWithDataLoader());
       return typeWiring;
}
`

**Comment by ruks** [comment]
@mheidt I'm still on version 1.11. In my graphQL schema, all the operations are query type and I need to execute all of them async on the server-side. So I tried to return `CompletableFuture<Item>` DataFetcher. So I changed the template and was able to achieve my requirements. 

I also noticed that this check `#if (${dataFetcher.completableFuture})` in the velocity template. But when I check the code this was derived automatically based on the operation and there wasn't any global config to make all the operations async.

Do you have any suggestions?

Thanks in advance.

**Comment by mheidt** [comment]
If it concerns all of your datafetcher, changing the template is a good idea.
In my case I needed aliasable batchloader oder batchloader that return a Long or String and not an object.
That's when I use CompletableFuture and the method I described above.

**Comment by ruks** [comment]
@mheidt thanks, yes I also thought the same, will use a custom template.

When I use the master, I got this error. Does anyone have an idea? 
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field executor in com.graphql_java_generator.client.GraphQLConfiguration required a bean of type 'com.graphql_java_generator.client.QueryExecutor' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

The following candidates were found but could not be injected:
	- Bean method 'queryExecutor' in 'GraphQLAutoConfiguration' not loaded because auto-configuration 'GraphQLAutoConfiguration' was excluded


Action:

Consider revisiting the entries above or defining a bean of type 'com.graphql_java_generator.client.QueryExecutor' in your configuration.


Process finished with exit code 1

```

Note that i'm using the default generated GraphQLServerMain.

**Comment by ruks** [comment]
The above issue is sorted and tested with the customized template and it working perfectly. I will be waiting for the next release.

**Comment by etienne-sf** [comment]
You can now check the 1.13 release

**Comment by ruks** [comment]
> You can now check the 1.13 release

Upgraded to 1.13 and work as expected. Hence i'm closing this issue. 
Thanks all for the help 👍
