### ISSUE TITLE
Setting http Authorization header

### ISSUE THREAD

**Issue by micharaze** [graphql-java-generator/graphql-maven-plugin-project#78]
I am using graphql-java-generator without spring for testing a graphql API. 

This is how I am creating the executor:
`queryExecutor = new QueryExecutor(address);`

and sending request:
`queryExecutor.LoginUser("", email, password, new Object[] {});`

This is working well. But how can I set an authentication token in the http header?

**Comment by etienne-sf** [comment]
Hello,

The easiest way is still to use the Spring capabilities. As you already have a non spring app, the easiest way is to encapsulate your non spring app into a spring app.

You can check this FAQ for more information on this: [Use the Spring capabilities with a non-spring App](#use-the-spring-capabilities-with-a-non-spring-app).

Etienne
