### ISSUE TITLE
Error while trying to run with custom templates

### ISSUE THREAD

**Issue by moshere-fb** [graphql-java-generator/graphql-maven-plugin-project#79]
Hi,
I'm trying to use custom templates with source path option as described here
https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/usage_customtemplates
I'm getting the following error
`Failed to execute goal com.graphql-java-generator:graphql-maven-plugin:1.14.1:graphql (default) on project graphql-client: Error when Generating object 'ArticleLink' into /Users/moshere/IdeaProjects/graphqlclient/target/generated-sources/graphql-maven-plugin/com/sf/graphql/ArticleLink.java`

![image](https://user-images.githubusercontent.com/56389331/116872487-9f819c80-ac1e-11eb-936c-407c297302aa.png)

Seems like template file resides correctly but it still failing. 

Thank you for your assistance
Moshe

**Comment by etienne-sf** [comment]
Hum,

There is almost no information about the error itself, there.

Can you execute the build with the "-e" parameter,  for instance:

```
mvn clean install -e
```

Etienne

**Comment by moshere-fb** [comment]
This is the error
```
Caused by: org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'graphql/customtemplates/object_type.vm.java'
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
        at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:392)
        at com.graphql_java_generator.plugin.generate_code.GenerateCodeGenerator.generateOneFile(GenerateCodeGenerator.java:495)
        ... 27 more
```
How I make the source available?

**Comment by etienne-sf** [comment]
Hum, I focused on the missing error message.

From the screen copy, the provided path is not the good one.

It must be the path relative to the folder where the pom is, that is: `src/main/java/graphql/customtemplates/object_type.vm.java`



As these are resources, you can put your graphql folder in the resources folder.
As they are useless at runtime, my opinion is that you can put them in a specific folder, which can be: `src/graphql`.

So, this leads to:
* Your template is in the `src/graphql/customtemplates/object_type.vm.java` (where src is a subfolder of the folder that contains your pom.xml file)
* Your pom configuration would be something like:

```xml
...
        <templates>
            <OBJECT>src/graphql/customtemplates/object_type.vm.java</OBJECT>
        </templates>
...

Etienne


NB: The doc states that the file is _relative to the project or module root_. I'll add the above info to make it more clear.

**Comment by etienne-sf** [comment]
The 1.16 added a check to display a clean error when there is an issue with the provided custom templates.

Etienne
