### ISSUE TITLE
There is a problem when using Boolean Type with property prefix "is"

### ISSUE THREAD

**Issue by xho22** [graphql-java-generator/graphql-maven-plugin-project#8]
graphql sdl:
`type Person {
  isPrimary: Boolean
}`

It will generate class below:
```java
public class Person  {
	@GraphQLScalar(graphqlType = Boolean.class)
	Boolean isPrimary;
	public void setIsPrimary(Boolean isPrimary) {
		this.isPrimary = isPrimary;
	}
	public Boolean getIsPrimary() {
		return isPrimary;
	}
}
```

But the correct getter/setter in JAVA is:
```java
        Boolean isPrimary;
        public Boolean getPrimary() {
            return isPrimary;
        }
        public void setPrimary(Boolean primary) {
            isPrimary = primary;
        }
```

The Getter/Setter method name is wrong.
After my testing, it will ran into a deserialization issue like below in production env.
`com.graphql_java_generator.client.response.GraphQLRequestPreparationException: <isPrimary,> is not a valid GraphQL name`

**Comment by etienne-sf** [comment]
Hello,

  I don't agree with your comment.

The getter for a xxxx atribute is getXxxx() or isXxxx()
So for a isPrimary attribute, the getter is getIsPrimary() or IsIsPrimary().

If you want the method to be getPrimary(), then your attribute must be named **primary** (not isPrimary).

Etienne

**Comment by xho22** [comment]
@etienne-sf 
I agree with part of your  suggestion.
I know I should use **primary** (not isPrimary), but sometimes there is not under my control.
It is possible that someone define a property name "isXXX" in sdl file, so it is just a problem in JAVA scope. You can not limit user definition.

And the code below is generated by My IDE (IDEA), it should be JAVA getter/setter standard although it looks such ugly.
```java
        Boolean isPrimary;
        public Boolean getPrimary() {
            return isPrimary;
        }
        public void setPrimary(Boolean primary) {
            isPrimary = primary;
        }
```

**Comment by etienne-sf** [comment]
Did you try to replace your Boolean isPrimary by primary ?


Or change:
type Person { isPrimary: Boolean }
to:
type Person { primary: Boolean }
?

**Comment by xho22** [comment]
@etienne-sf 
Yes, it works well when using **primary** instead of **primary**. But what if user cannot not want to change it? 
As I say in previous comment, it is possible that user can define any property name. Because this problem is just a Java problem (not native GraphQL)

In our scenario, sdl content was defined and generated by a python project. It support rest api for ui so that we couldn't change **isPrimary** due to it already be used for a long time.
