### ISSUE TITLE
Support for aliases in generated clients

### ISSUE THREAD

**Issue by rubena** [graphql-java-generator/graphql-maven-plugin-project#80]
Hi, 

I've used the current version to generate the client in a project that needs to make requests to a GraphQL server. Unfortunately, to get a property default value and its translation from the server in a single call I need to implement aliases. 
According to the readme, this is not yet implemented right? 
"The support for the full GraphQL specification (relay cursors, subscription, custom scalars, fragment, directive, GraphQL variables...). The only limitation is that aliases are not managed yet on client side. An enhancement will come about this issue."

When is this improvement expected to be developed?

**Comment by etienne-sf** [comment]
I was precisely thinking about the next dev to work on... !

:)

And yes, it's the last gap to fill, to fully respect the GraphQL spec.

So I'll start to work on this one now.

Étienne

**Comment by rubena** [comment]
Great to hear!

I'll be waiting for it.

Thank you!

**Comment by etienne-sf** [comment]
Hello,

I just released the 1.15 version.

You can now uses alias.

I'd be happy to have some feedback.

Etienne

**Comment by rubena** [comment]
It works great.

Thanks!

Ruben

**Comment by etienne-sf** [comment]
Thanks for this feedback!

:)
