### ISSUE TITLE
OnDemandDataLoaderRegistry since version 13

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#83]
Hello Etienne,

I was using 1.12.4 and wanted to upgrade to the latest version 1.16.

Unfortunately the plugin doesn't generate the 
OnDemandDataLoaderRegistry
anymore, so that it won't be found in the  GraphQLServerMain.

Did you change anything in that area, so that I have to adapt?

Cheers,
Markus

**Comment by etienne-sf** [comment]
Hi,

I don't understand your point, here.

The `GraphQLServerMain` class still contain:

```Java
	@Bean
	protected GraphQLSchema graphQLSchema() throws IOException {
		Resource res;
		StringBuffer sdl = new StringBuffer();
		res = new ClassPathResource("/generated_schema.graphqls");
		try(Reader reader = new InputStreamReader(res.getInputStream(), Charset.forName("UTF8"))) {
			sdl.append(FileCopyUtils.copyToString(reader));
		}
	
		TypeDefinitionRegistry typeRegistry = new SchemaParser().parse(sdl.toString());
	
		RuntimeWiring runtimeWiring = graphQLWiring.buildWiring();
		SchemaGenerator schemaGenerator = new SchemaGenerator();
		return schemaGenerator.makeExecutableSchema(typeRegistry, runtimeWiring);
	}
```

Do you mean that these lines are missing ?
Or that they don't compile ?

If it's the latter, you should check your dependencies: I embedded and updated the _graphql-java-spring-mvc_ as a module in the project.
Typically, you should have this dependency:

```xml
		<dependency>
			<groupId>com.graphql-java-generator</groupId>
			<artifactId>graphql-java-server-dependencies</artifactId>
			<version>1.16</version>
			<type>pom</type>
		</dependency>
```


Etienne

**Comment by mheidt** [comment]
with 12.5 this file is generated und not in a dependency
![image](https://user-images.githubusercontent.com/4159298/121707194-9e257880-cad6-11eb-9830-fce31a208fa3.png)

with version 13 and up that file is missing

**Comment by mheidt** [comment]
My parameters are
<addRelayConnections>false</addRelayConnections>
                            
                            
                            <copyRuntimeSources>true</copyRuntimeSources>
                            <generateBatchLoaderEnvironment>true</generateBatchLoaderEnvironment>
                            <packageName>de.lsy.cmon.aggregator.graphql</packageName>
                            <separateUtilityClasses>true</separateUtilityClasses>

**Comment by etienne-sf** [comment]
Hello,

Yes this file is no more generated.

As I said in my previous message, it is now embedded in the  graphql-java-spring-mvc as a module in the project.

So you must check that you have this dependecy into your project dependecies:

```xml
			<dependency>
				<groupId>com.graphql-java-generator</groupId>
				<artifactId>graphql-java-spring-mvc</artifactId>
			</dependency>
```

Instead of the graphql-java-spring-mvc coming from graphql-java.


This is automatic if you use the proper pom dependency for the plugin, which is:

```xml
		<dependency>
			<groupId>com.graphql-java-generator</groupId>
			<artifactId>graphql-java-server-dependencies</artifactId>
			<version>1.16</version>
			<type>pom</type>
		</dependency>
```

**Comment by mheidt** [comment]
Sorry, I didn't understand it correctly.
I just took notice of the number and thought, that the server dependency takes care of it.

**Comment by etienne-sf** [comment]
Yes the server dependency takes care of it.

If you're using the `graphql-java-server-dependencies`, you shouldn't even have notice this change.

Are you using it as a dependencyin your pom? Or something else?
