### ISSUE TITLE
schemaFileFolder of resources in external jar

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#84]
Hello Etienne,

I want to generate server and client in different modules but want to keep the graphqls files central.
That's why I moved them into a resouces/graphql_schema folder and included that jar as dependency of the graphql-maven-plugin.
Like I did for the template objects.
Now I thought, that I just had to enable this tag
`<schemaFileFolder>graphql_schema</schemaFileFolder>
`
Unfortunately no schema is found.

Thanks,
Markus

**Comment by etienne-sf** [comment]
Yes,

Currently the plugin only search into the local file system.

So you'll have to unzip you jar somewhere below the target folder, and use the `schemaFileFolder` plugin parameter, to tell it where to find your jar.

You can unzip your jar by using the [maven dependency plugin](https://maven.apache.org/plugins/maven-dependency-plugin/examples/unpacking-artifacts.html)

Etienne

**Comment by mheidt** [comment]
Thanks Etienne!
