### ISSUE TITLE
DateTime / LocalDateTime

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#85]
Hi,

I have a DateTime in my schema which I configured in the pom like

```
<customScalar>
    <graphQLTypeName>DateTime</graphQLTypeName>
    <javaType>java.time.LocalDateTime</javaType>
    <graphQLScalarTypeStaticField>
        com.graphql_java_generator.customscalars.GraphQLScalarTypeDateTime.DateTime
    </graphQLScalarTypeStaticField>
</customScalar>
```

Unfortunately I get a 
Exception while fetching data (...) : Can't transform the jsonParsedValue (java.util.Date) into a java.time.LocalDateTime

java.lang.RuntimeException: Can't transform the jsonParsedValue (java.util.Date) into a java.time.LocalDateTime
	at com.graphql_java_generator.util.GraphqlUtils.getArgument(GraphqlUtils.java:419)
	at com.graphql_java_generator.util.GraphqlUtils.getArgument(GraphqlUtils.java:356)
	at com.graphql_java_generator.util.GraphqlUtils.getArgument(GraphqlUtils.java:359)

I guess I am doing something wrong?

**Comment by etienne-sf** [comment]
The provided implementation is valid only for ´java.util.Date´

If you want to use a ´ java.time.LocalDateTime´, you'll have to implement or find a CustomScalarImplementation that maps to this class.

**Comment by mheidt** [comment]
Ok. I actually needed Instant in the end.
I wrote my own CustomScalarImplementation.
In case you want to provide one.

For Instant, this one is used instead of SimpleDateFormat
DateTimeFormatter formatter = DateTimeFormatter.ofPattern(DATE_PATTERN);

And Instant can parse itself:
Instant.parse((String) o)

**Comment by etienne-sf** [comment]
Can you publish it as a PR in the graphql-maven-plugin project ?

It should be in the same package as the ´java.util.Date´ custom scalar implementation.

**Comment by mheidt** [comment]
Surely I could. But we should discuss about this:

```
public class GraphQLScalarTypeInstant {
    /**
     * Custom Scalar for Instant management. It serializes datetimes in String, formatted as: yyyy-MM-dd'T'HH:mm:ss'Z'
     */
    public static GraphQLScalarType DateTime = GraphQLScalarType.newScalar().name("DateTime").description(
        "Custom Scalar for Instant management. It serializes datetimes in String, formatted as: yyyy-MM-dd'T'HH:mm:ss'Z'")
```
I used DateTime as scalarType in my first draft, so that I don't have to change the schema templates.

And I am undecided if this is good or not. On the one hand Instant is a typical JAVA class and translates to a generic "DateTime" term which suits better the GraphQL world. On the other hand, it won't be possible to handle Java DateTime and Instant in one project. But who would?

What's your oppinion?

**Comment by etienne-sf** [comment]
Yes,

It's a good question. 

The existing custom scalar implementation is really a date, no time (it's format is yyyy-mm-dd). 

And who would use both: no one, I agree. And is necessary, it's always possible to provide an alternative implementation, if needed. 

As your format is date and time, my opinion is that DateTime is a good name. 


And this would allow me to have both Date and DateTime in the same test project.

**Comment by mheidt** [comment]
Like this?
https://github.com/mheidt/graphql-maven-plugin-project/blob/master/graphql-java-runtime/src/main/java/com/graphql_java_generator/customscalars/GraphQLScalarTypeInstant.java

**Comment by mheidt** [comment]
I had to add a TimeZone to make it work:

 ```
DateTimeFormatter formatter = DateTimeFormatter.ofPattern(DATE_PATTERN)
                    .withZone(ZoneId.of("UTC"));
```
Should this be configurable?

**Comment by etienne-sf** [comment]
Hello,

It's a good point.

I let my brain think about this today. But it didn't choose !
:)

It would be better if it could be configured, of course. But this must remain simple.

It could be:
* A parameter in the application.yml or application.properties of Spring Boot, for instance. Something like: `graphql.customscalat.DateTime.format`
    * But this means that the Custom Scalar implementation has access to the Spring Context.  And it must still be compatible with application without Spring, which can occur on client side.
* A System property, with no link with Spring. But how to set it properly
* A setter seems better. But how o set it automagically ?

Any idea on your side ?


And if it's too complex, let's publish it as its, without open configuration.
I guess it would be possible to set

**Comment by etienne-sf** [comment]
I have a fourth idea, which seems better:

The implementation could provide two static getters:
- one without parameter, with your default pattern. 
- one with parameters. This one can be used in a static getter in the "user's" code. This last getter is the one that is declared in the Pom. 


Doing this allows to configure the custom scalar without any configuration stuff. 

IMHO, it is easier to use (and to develop, actually)

Étienne

**Comment by etienne-sf** [comment]
Hello,

I'm quite near to release a new version.

Do you plan to do a Pull Request for this DateTime custom plugin ?

Etienne
