### ISSUE TITLE
Need to be able to add additional ExchangeFilterFunctions to reactive client

### ISSUE THREAD

**Issue by markxj** [graphql-java-generator/graphql-maven-plugin-project#87]
In my client app, I need to be able to add some extra headers to all outgoing requests. With a reactive client this is done by adding a filter to the ClientBuilder or mutating an existing client.

As these are not exposed, there's no way to add the filters

**Comment by etienne-sf** [comment]
Hello,

The `com.graphql_java_generator.spring.client.GraphQLAutoConfiguration` Spring autoconfiguration class creates a `org.springframework.web.reactive.function.client.WebClient` bean.

Isn't this what you're looking for ?

Etienne

**Comment by markxj** [comment]
The GraphQLAutoConfiguration does create the WebClient bean but I have no ability to modify it to be able add extra filters to it

**Comment by etienne-sf** [comment]
Is think that the easiest way is that you create your WebClient Spring Bean with your filters. In this case, the GraphQL autoconfiguration class won't create it. 

I don't see an easy way to expose the WebClient builder, let you add filters to it, then build the WebClient from it. 
Or perhaps you have an idea on this point ?

Or it would be possible to "discover" filters, and add them to the WebClient. 
But then, I guess that if you have two GraphQL servers, the header you add will not be the same for them both.

**Comment by markxj** [comment]
Exactly - it ties in with the other issue I wrote up yesterday about accessing multiple servers with different urls.

Maybe add a constructor to the generated Query and Mutation Executors that allows a WebClient to be passed in - much the same as when passing a jersey client in the older code?

**Comment by etienne-sf** [comment]
I'm updating the auto configuration ´GraphQLAutoConfiguration´ class. 
I added a static class that returns a WebClient. It accept a list of ExchangeFilterFunction, so that you can create your own WebClient bean by just one method call, and provide your own list. 

I think or would do the trick.

**Comment by etienne-sf** [comment]
It is available in the 1.18, that has just been released.

Etienne
