### ISSUE TITLE
Maven dependency includes both GraphQL client and server dependencies causing No qualifying bean of type 'graphql.GraphQL'  when only used as client in Spring-Boot

### ISSUE THREAD

**Issue by hmottestad** [graphql-java-generator/graphql-maven-plugin-project#88]
`No qualifying bean of type 'graphql.GraphQL'` error if the `com.graphql-java-generator::graphql-java-runtime` dependency is used together with Spring-Boot when only using `generateClientCode`. 

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'defaultGraphQLInvocation': Unsatisfied dependency expressed through field 'graphQL'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'graphql.GraphQL' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

As I could understand the `com.graphql-java-generator::graphql-java-runtime`  isn't needed once the code is generated, but if it is removed then there are a bunch of missing dependencies:

Some examples of missing dependencies:
 - com.graphql_java_generator.exception.GraphQLRequestExecutionException
 - com.graphql_java_generator.GraphQLField
 - com.graphql_java_generator.annotation.GraphQLInputParameters

**Comment by hmottestad** [comment]
My fix has been to exclude the server dependencies:

```
        <dependency>
            <groupId>com.graphql-java-generator</groupId>
            <artifactId>graphql-java-runtime</artifactId>
            <version>${graphql-maven-plugin.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.graphql-java-generator</groupId>
                    <artifactId>graphql-java-server-dependencies</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by hmottestad** [comment]
Would it be a good idea to make `graphql-java-server-dependencies` and `graphql-java-client-dependencies` `provided` and tell users to include one or the other or both?

Or possibly just specify in the code to use `graphql-java-client-dependencies` (as type pom) instead of `graphql-java-runtime` if all the user wants is the client?

**Comment by hmottestad** [comment]
Related: https://github.com/graphql-java-generator/graphql-maven-plugin-project/issues/56

**Comment by etienne-sf** [comment]
Hello,

The standard use is of the dependencies:
* NOT use `graphql-java-runtime` as a dependency
* NOT use the `copyRuntimeSources` plugin parameter (et set it to _true_, its default value)
* Use either the `graphql-java-server-dependencies` or `graphql-java-client-dependencies`, depending on your case.

The main reason of the `copyRuntimeSources` plugin parameter, is that some people want to override part of the runtime for their own need. To do this, they create their own runtime.

For all other users, the above configuration is the good one.


Does it help ?

Etienne

**Comment by etienne-sf** [comment]
BTW, removing the `graphql-java-runtime`, and put the runtime in either the `graphql-java-server-dependencies` or `graphql-java-client-dependencies` is a good idea.
It would make things clear.

I'll do that for the 2.x versions.

**Comment by RichMacDonald** [comment]
Not wanting to hijack this thread but one legitimate use case for needing both client and server packages in the same VM is for Integration Tests in a build pipeline:
1. Start Server (requires server code)
1. Run integration tests via a Client (requires code code)
1. Shut down server.

I've been trying to do this with maven/spring unsuccessfully for some time now.

**Comment by etienne-sf** [comment]
> 
> 
> Not wanting to hijack this thread but one legitimate use case for needing both client and server packages in the same VM is for Integration Tests in a build pipeline:
> 
>     1. Start Server (requires server code)
>     2. Run integration tests via a Client (requires code code)
>     3. Shut down server.
> 
> I've been trying to do this with maven/spring unsuccessfully for some time now.

This is still an _hijack_, still !
;)

This is done in the three samples in the project. You can have a look in git: https://github.com/graphql-java-generator/graphql-maven-plugin-project/tree/master/graphql-maven-plugin-samples
Or checkout the code, and see how it works.

Take a look at the client projects, that execute the relevant server(s), then execute the integration tests.

Etienne
