### ISSUE TITLE
Duplicate Accept Header may Cause ResponseProcessingException

### ISSUE THREAD

**Issue by schulzp** [graphql-java-generator/graphql-maven-plugin-project#89]
Hi!

Thank you for a super useful plug-in! I'm using the graphql-maven-plugin to generate a client for integration-testing a GraphQL API. After updating the web-app, those tests failed with an `javax.ws.rs.client.ResponseProcessingException` caused by a response header `Content-Type: application/json,application/json`.

I dug a bit deeper and found the cause in [QueryExecutorImpl.java](https://github.com/graphql-java-generator/graphql-maven-plugin-project/blob/b239c4cefe657a81261f24a0cc02e1bc428823fe/graphql-java-runtime/src/main/java/com/graphql_java_generator/client/QueryExecutorImpl.java#L131):

```java
Invocation.Builder invocationBuilder = webTarget.request(MediaType.APPLICATION_JSON);
invocationBuilder.header("Accept", MediaType.APPLICATION_JSON);
```

The first line already results in `Accept: application/json`. The second line *adds* to the header multi-map, so when the request is finally sent, it reads `Accept: application/json,application/json`. Is this a bug?

**Comment by etienne-sf** [comment]
Thanks for the comment about the plug-in. 
:)

And yes,it looks very much like a bug!
I'll remove this line in the next version. 

Or perhaps you can do a Pull Request ?
It would make another contributor to the project!
;)

Étienne

**Comment by schulzp** [comment]
Thank you for your quick response, @etienne-sf! I created the [PR](#90) as requested. 😄
