### ISSUE TITLE
Can't access Principal the way RestController does

### ISSUE THREAD

**Issue by avishail** [graphql-java-generator/graphql-maven-plugin-project#91]
I'm migrating some old @RestController (with Spring Boot) class to GraphQL using this plugin. The problem I'm facing is that I can't have access to Principal and to the HttpServletRequest and HttpServletResponse that Spring injected to the old @RestController.

I've found a way to get it from Spring by accessing the thread locals but I also found some complains that this isn't reliable enough.

I think we should have a reliable way to pass all Spring injections to the DataFetcherImpl classes in case they will be needing those classes.

**Comment by etienne-sf** [comment]
I agree with you.
But I see no simple answer here.

In the wiki (https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/server_faq#howto-provide-your-graphql-executioninputcustomizer-executionresulthandler-graphqlinvocation-graphqlcontroller-and-jacksonjsonserializer) there is a list of the Spring component that you can override.

Perhaps you can override the `GraphQLController`. It's the RestController that manages the incoming GraphQL requests.
