### ISSUE TITLE
Change ID Implementation As UUID

### ISSUE THREAD

**Issue by avishail** [graphql-java-generator/graphql-maven-plugin-project#92]
Hi

It is more of a question than an issue since I wasn't able to find a solution after some time of digging around.

My GraphQL server touches number of tables in my database, each table has its own unique identifier. It can be a string (email for example) or numeric ID etc. When I'm constructing the relevant type, I can't map those different types of IDs into Java's UUID object in a way I can ensure there will be no collisions.

In addition, since my service is stateless and I have multiple instances, I can't maintain a mapping between UUIDs and Objects so I'll be sure that always "a@a.com" will be mapped to the same UUID.

So, my question is, how can I replace the ID implementation (UUID) with String for example because when I replaced id: ID! with id: String! the interfaces started to change and for example batchLoader gone etc.

What's the right way to do it?

**Comment by etienne-sf** [comment]
I guess you're using the `server` mode of the plugin.

The `javaTypeForIDType` allows you to define to which Java type UUID should be mapped.

You can have a check on all available parameters here: https://graphql-maven-plugin-project.graphql-java-generator.com/graphql-maven-plugin/generateServerCode-mojo.html

Etienne
