### ISSUE TITLE
Issue with jackson deserialization

### ISSUE THREAD

**Issue by bugsnatch** [graphql-java-generator/graphql-maven-plugin-project#93]
Hi, I'm using this plugin to handle graphql client request built from the introspection query. I'm using it in a non spring framework. Given the following schema:

```
 type Query {
  indirectPortal(
        "IsoCode"
        language: String!
    ): IPData
}
type IPData {
    translations: JSON
}
```
I've defined JSON as custom scalar:
```
    customScalars = [[
         graphQLTypeName   : "JSON",
         javaType                    : "java.util.Map",
         graphQLScalarTypeStaticField: "graphql.scalars.object.JsonScalar.INSTANCE"
     ]]
```
which is provided by 
`    compile 'com.graphql-java:graphql-java-extended-scalars:2021-08-03T09-10-50-aff4d46'`

I'm able to execute the query however it generates GraphQLRequestExecutionException

```
Caused by: com.graphql_java_generator.exception.GraphQLRequestExecutionException: Error when executing query 
<{"query":"query{indirectPortal(language:\"en\"){translations __typename}}","variables":null,"operationName":null}>: 
Non managed JSON token: START_OBJECT
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: Query["indirectPortal"]->IPData["translations"])
	at com.graphql_java_generator.client.QueryExecutorSpringReactiveImpl.execute(QueryExecutorSpringReactiveImpl.java:173)
```

The response based on the above query is as follow:
```
{
  "data": {
    "indirectPortal": {
      "translations": {
        "level0standard": "value0standard",
        "nestedCategory": {
          "level1standard": "value1standard",
          "level2category": {
            "standardField": "value2standard"
          }
        }
      },
      "__typename": "IPData"
    }
  }
}
```

The 'key' can be randomly defined, which is the reason why the schema is using JSON as type

Is there something wrong with my setup or is there any issue with version 1.17 ?
thx

**Comment by etienne-sf** [comment]
Hello,

Taken from the GraphQL specifications: _Scalar types represent primitive leaf values in a GraphQL type system. GraphQL responses take the form of a hierarchical tree; the leaves on these trees are GraphQL scalars._

So you may not use a Custom Scalar that return an object. Only a JSON valus is expected, which is the reason for this error.

So the issue is now to have dynamic keys.


What I would do is to create a schema with something like this:

```
type SimpleValue {
  value: String!
}

type ObjectValue {
  values: [SimpleValue]
}

union Value = SimpleValue | ObjectValue

type Translation {
  key: String
  value: [Value]
}

type Translations {
  translations: [Translation]
}

type IPData {
    translations: Translations
}
```

**Comment by etienne-sf** [comment]
My first answer is not correct. 

AFAIU, you need a recursive structure. But I don't know enough about your use case to define a proper model.

So here is another try (but you'll fine better anwers on the net):
```
type SimpleValue {
  key: String!
  value: String!
}

type Translation {
  simpleValues: [SimpleValue]
  objectValues: [ObjectValue]
}

type Translations {
  translations: [Translation]
}

type IPData {
    translations: Translations
}
```
