### ISSUE TITLE
Subscriptions with token base authentication

### ISSUE THREAD

**Issue by avishail** [graphql-java-generator/graphql-maven-plugin-project#94]
I'm using my graphql server in a token base auth mode. I was able to handle the GraphQL HTTP requests by adding filters that will search for the Authorization header and will do the authentication before the actual GraphQL implementations will be called so all in all, when I handled the actual data fetch/mutation I was authenticated.

But, when working with subscriptions and Websockets things are slightly different. When establishing the connection, the filter will be called and I can authenticate the flow, but, when I'm sending the subscription query, the filters won't be called and I have no way to authenticate the call.

Since the WebsocketHandler is auto generated, I can't change it and add the authentication logic at the first line of handleTextMessage.

When I'm hitting the subscription implementation class, it is too late and I cant get a hold of the Sebsocket session which holds the metadata for authenticating the call.

Any idea what I can do here?
Thanks!

**Comment by avishail** [comment]
BTW, the solution I used for now is to take WebSocketConfig out of the auto generated files and to modify it so I'll be able to authenticate before the handler handle a message.

**Comment by etienne-sf** [comment]
Hello,

You provide very few information on what's done in your project. 
I guess you're using the GraphQL-maven-plug-in for your server. 
Which version ?

The sample provided in the allGraphQLCases projects (client and server) works with OAuth2. 

This includes a subscription. 

Did you check what's done in this project ?

Étienne

**Comment by avishail** [comment]
I went over it all (Forum, Starwars, allGraphQLCases etc) and didn't find OAuth + Subscription example.

My use case is that I have a GraphQL server in one domain and a web client on another domain. The web client is doing some authentication against the GraphQL server and gets a JWT token which has to be passed with every request.

I'm able to run a filter (OncePerRequestFilter) on every HTTP request, grab the token from the Authorization header and do the actual authentication before hitting the GraphQL controller.

But, when dealing with subscriptions, things are slightly different since when the web client sends a subscription request through the websocket, the filter logic won't run (since this isn't an HTTP request) and I have no way to grab the token and to authenticate this request.

As I mentioned before, a possible solution in my problem would be to add some logic to the WebSocketConfig but since this file is "auto generated" I can't modify it.

I'm using version 1.15 of the plugin and yes, I'm using the server mode.

**Comment by etienne-sf** [comment]
Hello,

The Subscription in the allGraphQLCases server sample is protected by OAuth.

If you try to execute a subscription without a valid OAuth token, you get a 401 http error code.

There is an issue, still, that this error is not properly returned to the caller, in the client code of the plugin. 

But the important point is that the server is properly secured.


From the commit date, it should be available in the 1.15 version. But I recommand that you upgrade to the 1.17 version (the last one) to be sure of this behaviour.

Etienne
