### ISSUE TITLE
http queries being overridden by oauth setup

### ISSUE THREAD

**Issue by allense11947** [graphql-java-generator/graphql-maven-plugin-project#96]
We have a project that has multiple ontologies and endpoints, one of which requires oauth access.  The generated code is enabled like this:

`
// Unsecured setup
    @Bean
    public UnsecuredQueryExecutor unsecuredQueryExecutor()
    {
        return new UnsecuredQueryExecutor (httpUnsecuredUrl);
    }

// Secured setup
    @Bean("serverOAuth2AuthorizedClientExchangeFilterFunctionSecured")
    public ServerOAuth2AuthorizedClientExchangeFilterFunction serverOAuth2AuthorizedClientExchangeFilterFunctionSecured(
            ReactiveClientRegistrationRepository clientRegistrations
    )
    {
        ServerOAuth2AuthorizedClientExchangeFilterFunction oauth = new ServerOAuth2AuthorizedClientExchangeFilterFunction(
                clientRegistrations, new UnAuthenticatedServerOAuth2AuthorizedClientRepository());
        oauth.setDefaultClientRegistrationId("oauthclientid");
        return oauth;
    }
`

What I was seeing was that the UnsecuredQueryExecutor was getting the oauthclient setup, including the secured url and credentials.  After looking into this it seemed the unsecured executor's GraphQLConfiguration field was first being set by the constructor, then overridden by a bean generated by the Secure setup.

I solved this by adjusting the client_query_mutation_executor.vm.java template to change the GraphQLConfiguration field from field injection to a method injection like this:

`
        @Autowired
        @Qualifier("graphQLConfiguration${springBeanSuffix}")
        public void setGraphQLConfiguration(GraphQLConfiguration graphQLConfiguration)
	{
		if (this.graphQLConfiguration${springBeanSuffix} == null) {
			this.graphQLConfiguration${springBeanSuffix} = graphQLConfiguration;
		}
	}
`

I'm not convinced this is the best solution, but it worked.  The unsecured queries were http based and going to the right endpoint after this and I stopped getting errors from the secured server about invalid queries.

**Comment by etienne-sf** [comment]
Hello, 

Thanks for the correction proposal.
Did you try to just add the `@Qualifier` to the `graphQLConfiguration${springBeanSuffix}` field ?
(instead of adding an autowired setter)

This should be enough.

This what is done in the commit I just did.
It will be available in the 17.1 release that I'm about to do this Week End.

Etienne

**Comment by allense11947** [comment]
I tried that just now and it worked great!  Thanks for the help.

**Comment by etienne-sf** [comment]
Excellent !
:)
