### ISSUE TITLE
How to customize the outgoing request

### ISSUE THREAD

**Issue by abaveja313** [graphql-java-generator/graphql-maven-plugin-project#99]
Hi! Thanks so much for all the help already... but I am having a little trouble with one specific use case. My server needs a special header (on a per-request basis) in order to hit the GraphQL endpoint, and I am unsure how to go about adding that header within this framework. Is it possible for us to use our own webclient or expose a builder within the SpringConfiguration class? What would be the best practice to add headers/info at invocation time (dynamic?)

Again, thanks so much for the help thus far! 

Best,
Amrit

**Comment by etienne-sf** [comment]
Did you take a look at the wiki ?

There is a page that explains how to personalize the plug-in behavior (in the Client section, in your case). 
You can add Spring filters. I think (but did not search for that) that this is the best way to add headers to your requests. 

Étienne
